### ISSUE TITLE
Regression in 2022.7.0 for local file handling with no bytes copy

### ISSUE THREAD

**Issue by evamaxfield** [fsspec/filesystem_spec#1004]
Hey!

Seems like 2022.7.0 creates three errors in our test suite: https://github.com/AllenCellModeling/aicsimageio/runs/7566883918?check_suite_focus=true

Checked the version diffs from the yesterday's Check Upstreams and the only five package version changes were:
* `attrs-21.4.0` -> `attrs-22.1.0`
* `fsspec-2022.5.0` -> `fsspec-2022.7.0`
* `jsonschema-4.7.2` -> `jsonschema-4.8.0`
* `s3fs-2022.5.0` -> `s3fs-2022.7.0`
* `virtualenv-20.16.1` -> `virtualenv-20.16.2`

Since it's a file reading issue, the only ones that make sense to look at are fsspec or `s3fs`, from the test suite it seems like we were running local read tests and not remote read tests which to me says `fsspec` change likely culprit.

Looking through the changelog I think the likely culprit is #995 / #999 -- it also makes sense because I think @eode was working on some file reading with AICSImageIO stuff too??

Not entirely sure how to test because the error we receive on the other end is a `ValueError: seek of closed file` maybe @eode has ideas??

Much like our current "Test Upstreams" GH Action I am going to add fsspec and s3fs to the libraries tested to catch these before release.

**Comment by martindurant** [comment]
Is there any chance you can make a self-contained reproducer? I am finding it difficult to follow the code from that very long traceback. I have not managed to run the test suite locally.

**Comment by evamaxfield** [comment]
> Is there any chance you can make a self-contained reproducer? I am finding it difficult to follow the code from that very long traceback. I have not managed to run the test suite locally.

Can I use AICSImageIO for it? If so, I think I can probably make one. The `MemoryFile` stuff from #995 and #999 are a bit over my head unfortunately (should probably learn at some point though)

**Comment by martindurant** [comment]
I seem to have aicsimageio installed, but I didn't succeed in downloading the test data (scripts/download_test_resources.py failed with 400).

**Comment by martindurant** [comment]
I seem to have aicsimageio installed, but I didn't succeed in downloading the test data (scripts/download_test_resources.py failed with 400).

**Comment by evamaxfield** [comment]
Three line reproducer with AICSImageIO:

```bash
pip install aicsimageio
```
```python
from aicsimageio import AICSImage
img = AICSImage("s_1_t_10_c_3_z_1.tiff")
img.get_image_dask_data("CYX").compute()
```

Only occurs when we are doing a partial / delayed file read (any of the `dask` related calls basically)

File used above found here: https://open.quiltdata.com/b/aics-modeling-packages-test-resources/tree/aicsimageio/test_resources/resources/s_1_t_10_c_3_z_1.tiff

Click the "Download File" button in the upper right

**Comment by martindurant** [comment]
In fact https://github.com/fsspec/filesystem_spec/pull/973 was the culprit - unintended consequences of a LocalFileOpener being "pathlike" by virtue of implementing __fspath__ , but a real python builtin local file not doing that. So I removed it, there was no reason to have it.

**Comment by evamaxfield** [comment]
Interesting! Sorry for pointing in the wrong direction. Just seemed so likely that @eode crossover between all three of the projects would have been the culprit.

Thanks for the quick fix!
