### ISSUE TITLE
`fsspec.core.url_to_fs` doesn't handle `S3://`-like paths (capital letter in protocol)

### ISSUE THREAD

**Issue by prutskov** [fsspec/filesystem_spec#1009]
**Problem description**

Function `fsspec.core.url_to_fs` can't create filesystem from `S3://`-like path, but can from `s3://`-like path (lower case is working).

**Reproducer**

```python
import fsspec

path = "S3://modin-datasets/testing/multiple_csv/test_data*.csv"
print(fsspec.core.url_to_fs(path))
```

Error trace:
```shell
File ~\.conda\envs\modin\lib\site-packages\fsspec\core.py:408, in url_to_fs(url, **kwargs)
    406 else:
    407     protocol = split_protocol(url)[0]
--> 408     cls = get_filesystem_class(protocol)
    410     options = cls._get_kwargs_from_urls(url)
    411     update_storage_options(options, kwargs)

File ~\.conda\envs\modin\lib\site-packages\fsspec\registry.py:225, in get_filesystem_class(protocol)
    223 if protocol not in registry:
    224     if protocol not in known_implementations:
--> 225         raise ValueError("Protocol not known: %s" % protocol)
    226     bit = known_implementations[protocol]
    227     try:

ValueError: Protocol not known: S3
```

**Comment by martindurant** [comment]
I think this is correct functioning, the protocol should be given as lower case, and we should not make any extra effort to deal with situations where it isn't.

**Comment by pyrito** [comment]
@martindurant even though the protocol is technically not correct, capitalization shouldn't make a difference right? There's no underlying difference between `S3://` and `s3://` from what I know. Couldn't `fsspec` just handle these cases by doing something like `protocol.lower()`?

**Comment by martindurant** [comment]
> capitalization shouldn't make a difference

It's an extra thing that we would need to take care of and add extra complexity into the codebase, as well as extra CPU time in the (simple) checks required. In general, file paths should and are case sensitive. I am not aware of any case where the protocol string itself is upper case, but this might well happen.

If there is wider support for putting in a `.lower()` we could do it, but I personally prefer to call this user error, for which the exception message (protocol not known) is suitable.
