### ISSUE TITLE
spec _parent function crashes on receiving Path due to rstrip

### ISSUE THREAD

**Issue by kasuteru** [fsspec/filesystem_spec#1020]
The `parent` function (see code below) seems currently flawed and crashes in certain cases.

If you look at the function, the logic usually is as follows: Call `_parent` -> This immediately calls `_strip_protocol` -> This calls `stringify_path`, which converts anything e.g. pathlib.Path into a str path. 

**However**, the actual very first thing `_parent` does is calling `path.rstrip` - and that makes the whole thing crash if `_parent` ever receives anything but an already stringified path:

https://github.com/fsspec/filesystem_spec/blob/3f8c8e07219622e68e428214300a548ab7a2f8b7/fsspec/spec.py#L950-L957

So _either_ `_parent` is only ever expected to receive a str (which should be made clear in the function description), but then, there is no need to call `_strip_protocol` inside it again, or, and more likely, `rstrip` shouldn't be called here.

So the question is, why is `rstrip` in there, and can it be deleted / moved somewhere else? Forcing `rstrip` is causing this kind-of-related issue as well:  

https://github.com/fsspec/filesystem_spec/issues/945

**Comment by kasuteru** [comment]
Looks like `_strip_protocol` anyways calls rstrip in line 184 (correctly, after converting to str), so the use of `path.rstrip` in `_parent` seems redundant anyways? 

https://github.com/fsspec/filesystem_spec/blob/3f8c8e07219622e68e428214300a548ab7a2f8b7/fsspec/spec.py#L169-L186

What is the test coverage of this library? Can I just remove the `rstrip` and write a PR, or do I need to investigate deeper to fix this?

**Comment by martindurant** [comment]
> What is the test coverage of this library? Can I just remove the rstrip and write a PR, or do I need to investigate deeper to fix this?

It would be nice to build some additional tests specifically around parent and strip protocol to a) expose the failure you would have seen without your change and b) make a lost of expected outcomes from the two functions for a range of inputs. Note that there are other implementations of strip_protocol in some backends.

**Comment by kasuteru** [comment]
Let's see whether the tests pass for the change (See PR). If they do, I will try to create a few additional ones to prevent this in the future.
