### ISSUE TITLE
Implement `topdown=True|False` for `walk(...)`

### ISSUE THREAD

**Issue by hozblok** [fsspec/filesystem_spec#1042]
This can be useful for working with files from the bottom to the up in the entries tree.

Current realization of the [walk(...)](https://github.com/fsspec/filesystem_spec/blob/2633445fc54797c79a7ac96d213bd24dfbdfcdc2/fsspec/spec.py#L364) does not support `topdown=False` as it is in [cpython walk(...)](https://github.com/python/cpython/blob/934b25dcc492dcbca4da9d63d0d71dc940fc0375/Lib/os.py#L282)

Is there anything preventing us from adding this argument?

**Comment by martindurant** [comment]
You are very welcome to propose a PR implementing the option!

**Comment by hozblok** [comment]
> You are very welcome to propose a PR implementing the option!

Hi @martindurant, I'll try to make it in a week)

**Comment by hozblok** [comment]
Hi @martindurant, sorry, plans have changed drastically due to force majeure, I won't be able to do it anytime soon :(
