### ISSUE TITLE
cat_file (or equivalent) that returns the contents in text mode

### ISSUE THREAD

**Issue by skshetry** [fsspec/filesystem_spec#1045]
Currently, `cat_file` only returns the contents of the file as bytes. The decoded content as a string would be really useful.

I see two ways to implement this:
1) extend `cat_file()` with `mode`/`encoding`/`errors` kwargs to pass it down to `open`.
2) introduce [`read_text()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_text) or similar API.

Happy to go with either option and create a PR.

**Comment by martindurant** [comment]
I am not principally opposed, but it seems like a really easy thing to do already, using either cat(...).decode() or open(..., mode="rt"). Since the read_text() API is a pathlib thing, you could ask universal_pathlib to do  it.

**Comment by skshetry** [comment]
> but it seems like a really easy thing to do already, using either cat(...).decode()

Yes, it is easy to do, but it's not convenient and reading text is a common filesystem operation. We could say the same for `cat_file` to be replaced with `with fs.open(): return f.read()`, but it's really convenient to use.

> Since the read_text() API is a pathlib thing, you could ask universal_pathlib to do it.

I was only suggesting the API name. There's also [`PyFileSystem.readtext()`](https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.readtext) for comparison.

That said, I can understand the reluctance to add more methods/operations since `cat_file` is _overloaded_, 
and adding text modes in `cat-file` might affect other APIs to also support strings (eg: `cat`/`pipe`, etc.). 🙂

**Comment by martindurant** [comment]
If you can put it into an implementation that does not confuse o clutter the API too much, I daresay we could keep it. That probably means a new method (+writetext), rather than an argument to `cat`.
