### ISSUE TITLE
The arrow_hdfs protocol violates rfc3986 in urllib

### ISSUE THREAD

**Issue by hallenmaia** [fsspec/filesystem_spec#1050]
According to [rfc3986](https://www.rfc-editor.org/rfc/rfc3986#section-3.1), schema names consist of a sequence of characters starting with a letter and followed by any combination of letters, digits, plus ("+"), period ("."), or hyphen ("-") .

The new HDFS implementation violates this rule as the protocol was defined as `arrow_hdfs` in registry.py: 

https://github.com/fsspec/filesystem_spec/blob/742a103849adf2d0c9f3ad3fe08010d8de688268/fsspec/registry.py#L132

Thus, it is difficult to validate that a url is being provided correctly. For example:

```python
import urllib.parse

urllib.parse.urlsplit("arrow_hdfs://server/path")
SplitResult(scheme='', netloc='', path='arrow_hdfs://server/path', query='', fragment='')
```

This problem can be worked around by changing the protocol name from `arrow_hdfs` to `arrow-hdfs`:

```python
import urllib.parse
urllib.parse.urlsplit("arrow-hdfs://server/path")
SplitResult(scheme='arrow-hdfs', netloc='server', path='/path', query='', fragment='')
```

**Comment by martindurant** [comment]
@efiop , time to ditch "legacy" hdfs finally?

**Comment by efiop** [comment]
@martindurant Yeah, let's ditch it.

@hallenmaia would you be interested in contributing a PR for that?

**Comment by martindurant** [comment]
Correct, "arrow_hdfs" will replace the current "hdfs", which should be deleted. The entry for "arrow_hdfs" should remain in the known implementations for a while, though.

**Comment by hallenmaia** [comment]
PR in progress 🚀: https://github.com/hallenmaia/filesystem_spec/tree/issue-1050

**Comment by martindurant** [comment]
Thank you - let us know when you want a review.

**Comment by hallenmaia** [comment]
I'm just not sure about this:

https://github.com/hallenmaia/filesystem_spec/blob/9dc76b65bdea225c98419874525191b49b3eec78/fsspec/registry.py#L272

And in your test:

https://github.com/hallenmaia/filesystem_spec/blob/9dc76b65bdea225c98419874525191b49b3eec78/fsspec/tests/test_registry.py#L110

**Comment by martindurant** [comment]
The deprecation warning and its test can stay, as it won't appear for "hdfs", now pointing to the new version.
