### ISSUE TITLE
Q: how to make caching of http URLs agnostic of authentication query args in the URL?

### ISSUE THREAD

**Issue by yarikoptic** [fsspec/filesystem_spec#1073]
we advise users to use fsspec to access data on S3 with local caching via http urls. https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html#streaming-method-2-fsspec 

```python
# first, create a virtual filesystem based on the http protocol and use
# caching to save accessed data to RAM.
fs = CachingFileSystem(
    fs=fsspec.filesystem("http"),
    cache_storage="nwb-cache",  # Local folder for the cache
)

# next, open the file
with fs.open(s3_url, "rb") as f:
    with h5py.File(f) as file:
     ....
```

which works nicely - thank you!  Fun use case comes whenever we have some content which is not public and thus that s3_url would be minted with temporary credentials for the access embedded.  If I look inside the `nwb-cache/cache` having accessed public and private URLs (hopefully I sensored all private metadata ;)):

```
In [22]: print(json.dumps(eval(re.sub('(X-Amz-Credential|X-Amz-Signature)=\w*', '\\1=___SENSORED___', str(pickle.load(open('nwb-cache/cache', 'rb'))))), indent=4))
{
    "http://dandiarchive.s3.amazonaws.com/blobs/43b/f3a/43bf3a81-4a0b-433f-b471-1f10303f9d35?versionId=C1uOWMhd6uxiKUQG.U8xkxeYb.EySYbS": {
        "original": "http://dandiarchive.s3.amazonaws.com/blobs/43b/f3a/43bf3a81-4a0b-433f-b471-1f10303f9d35?versionId=C1uOWMhd6uxiKUQG.U8xkxeYb.EySYbS",
        "fn": "0928ea3fb4d189cbde2c3cd3b575b8f6eff9346a202526686bce40906c750770",
        "blocks": true,
        "time": 1659621832.986077,
        "uid": "e4a9a5a0418d6a526fb5d9744605eaea",
        "blocksize": 5242880
    },
    "https://dandiarchive-embargo.s3.amazonaws.com/000344/blobs/127/efb/127efb7b-4261-4f91-80f3-43ba23f3f9f1?response-content-disposition=attachment%3B%20filename%3D%22sub-private.dat%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=___SENSORED___%2F20221013%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20221013T182550Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=___SENSORED___": {
        "original": "https://dandiarchive-embargo.s3.amazonaws.com/000344/blobs/127/efb/127efb7b-4261-4f91-80f3-43ba23f3f9f1?response-content-disposition=attachment%3B%20filename%3D%22sub-private.dat%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=___SENSORED___%2F20221013%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20221013T182550Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=___SENSORED___",
        "fn": "ba14e62ea29043a39dc224e68447430526bebf35c54eb1da36b8be133dfd9b3c",
        "blocks": true,
        "time": 1665685552.2290783,
        "uid": "c202b9617e798d747add99d2755033be",
        "blocksize": 5242880
    }
}

```

I see that URL is stored as is, so if I re-request with updated URL (new credentials) --it would be cache miss and we would not use cache any longer.

What is the best way to accomplish mission for us/fsspec here?

- may be fsspec should provide helpers/mode/switches of stripping (specific?) query args?
- should we overload something (what then?) for the cache to figure out a stripped down "cache path" so we get cache hits? (should it be overload of `_strip_protocol`  or smth else)

Thanks in advance for guidance.

**Comment by martindurant** [comment]
In the case that the extra information is passed as parameters in the URL, you can work around this by using `params=` in the HTTP filesystem constructor (for all requests) or in `open()` (used for the specific file). I'm pretty sure this works, and will leave only the path part of the URL as they key for the cache.

We don't have a general way to specify which part of the path being accessed gets used by the caching, or any other way to map between paths and cached file names. The only flag is `same_names` (in the constructor of the caching filesystem), which I don't suppose will do the right thing for you.

**Comment by yarikoptic** [comment]
> In the case that the extra information is passed as parameters in the URL, you can work around this by using `params=` in the HTTP filesystem constructor (for all requests) or in `open()` (used for the specific file). I'm pretty sure this works, and will leave only the path part of the URL as they key for the cache.

very nice -- thank you!  FTR following solution worked for me (note -- needed to unquote since then params get quoted by fsspec I guess):

```python
s3_url_parts = s3_url.split('?', 1)
from urllib.parse import unquote
with fs.open(s3_url_parts[0], "rb", params=unquote(s3_url_parts[1])) as f:
```

overall -- thanks for the answer again!

**Comment by yarikoptic** [comment]
seems to work this code on direct download url! try with hdf5 etc

```python
from dandi.dandiapi import DandiAPIClient
import fsspec
import pynwb
import h5py
from fsspec.implementations.cached import CachingFileSystem
import sys
import re

dandiset_id = '000344' # (len(sys.argv) > 1 and sys.argv[1]) or '000006'  # ephys dataset from the Svoboda Lab
filepath = 'sub-private/sub-private.dat'  # (len(sys.argv) > 2 and sys.argv[2]) or  'sub-anm372795/sub-anm372795_ses-20170718.nwb'  # 450 kB file

# TODO: make helper
from dandi.keyring import keyring_lookup
client_name = 'dandi'
app_id = f"dandi-api-{client_name}"
keyring_backend, api_key = keyring_lookup(app_id, "key")
if not api_key:
    raise ValueError("empty key")
# fs._session.headers.update({"Authorization": f"token {api_key}"})

fs = CachingFileSystem(
    fs=fsspec.filesystem("http",
                         client_kwargs={'headers': {"Authorization": f"token {api_key}"}}
                         ),
    cache_storage="nwb-cache",  # Local folder for the cache
)

with DandiAPIClient() as client:
    client.dandi_authenticate()
    asset = client.get_dandiset(dandiset_id, 'draft').get_asset_by_path(filepath)
    down_url = asset.get_content_url(follow_redirects=0)
    print(f"{dandiset_id}/{filepath} has {down_url}")

with fs.open(down_url, "rb") as f:
    f.seek(2)
    print("Read some byte ", f.read(1))
```

with output

```
$> python embargo_url4_fsspec.py        
000344/sub-private/sub-private.dat has https://api.dandiarchive.org/api/assets/8f998a62-ac4c-465d-9989-656c90fb4668/download/
Read some byte  b'r'
```
```
