### ISSUE TITLE
Lists in project docs rendered incorrectly

### ISSUE THREAD

**Issue by ianthomas23** [fsspec/filesystem_spec#1083]
The project changelog at https://filesystem-spec.readthedocs.io/en/latest/changelog.html isn't rendered correctly as the unordered lists do not have bullet points and are spaced too far apart. Screenshot:

<img width="531" alt="Screenshot 2022-10-25 at 14 32 00" src="https://user-images.githubusercontent.com/580326/197786981-a3e860a7-fb78-4242-a834-5beca8875a8e.png">

This is apparently a well-known problem related to `sphinx-rtd-theme` and `docutils`: https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file

If I pin `docutils<0.17` and generate the docs locally then the problem is fixed. I think this is probably the best temporary solution until up-to-date `sphinx-rtd-theme` conda packages are available.

The question is where to put the pin? I think it should go in `docs/environment.yml` but it is not clear to me if the docs get built in CI and automatically uploaded or if it is a more manual process.

**Comment by martindurant** [comment]
Yes, CI should build and push the docs on every merge.
