### ISSUE TITLE
A few documentation questions about path and seperator

### ISSUE THREAD

**Issue by leoleoasd** [fsspec/filesystem_spec#1098]
Hi all, I have a few questions about the current implementations:

1. I noticed there is a `sep` attribute in `AbstractFileSystem`. But all built-in implementations use `/`, even for `LocalFileSystem` on windows, right? 
2. Should paths passed into `fs.xxx` have protocols? For example, I saw some implementations calls `_strip_protocol` for paths, and some don't (for example, other methods in `ArrowFsWrapper` calls it, but not for `ls` [see arrow.py](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/arrow.py#L61) and #1086). Should they be consistent? If they should, we need to fix current implementations and document this change somewhere.

**Comment by martindurant** [comment]
Correct, `sep` is always "/". Originally, we had `os.sep` for the local filesystem, but found this unworkable, so the attribute is just a hangover and not useful. I don't think it's referenced anywhere.

Seconds, filesystems should normally call _strip_protocol and allow full URLs passed in. You are welcome to make a PR to HDFS to make sure this works there too.

**Comment by leoleoasd** [comment]
Should we clarify this in the documentation? Or is it already written in there but I missed them?

**Comment by martindurant** [comment]
If it is in the docs (I am not sure), but you didn't find it, then it is not clear enough! Since we are talking about an attribute which is no longer useful, probably a comment in a code where it is defined is enough.

**Comment by leoleoasd** [comment]
marking sep as deprecated should be enough?
And should we also state in the document that methods like ls or touch in fs should also accept url as it's parameter?

**Comment by martindurant** [comment]
> should we also state in the document that methods like ls or touch in fs should also accept url

Yes, and probably this belongs in AbstractFileSystem's docstrings
