### ISSUE TITLE
Interested to add types?

### ISSUE THREAD

**Issue by jdonnerstag** [fsspec/filesystem_spec#1114]
I like types and if there is interest, I could start adding them. 
Any specific developer guides I need to follow?

**Comment by martindurant** [comment]
There is, I think, an existing issue for this. 
I am not opposed, but there is no guide (since we don't have types yet) and many places where Any is the only reasonable options - which is no help at all. I wish you the best!

**Comment by yarikoptic** [comment]
FWIW typing might have helped to prevent error exhibited itself in https://github.com/fsspec/filesystem_spec/issues/1107#issuecomment-1313988529

**Comment by ianthomas23** [comment]
There are a number of issues about adding type annotations. I am closing this as a duplicate of #625 as that has the most relevant discussion.
