### ISSUE TITLE
Correctly handle maxdepth kwarg

### ISSUE THREAD

**Issue by ianthomas23** [fsspec/filesystem_spec#1135]
As identified in discussion of PR #1128, `maxdepth` kwarg that is used in `walk` and related functions can be improved in two ways:

- Raise as an error if `maxdepth < 0`.
- `maxdepth=0` should be handled differently to `maxdepth=1`.

**Comment by martindurant** [comment]
Is maxdepth=0 useful for anything?

**Comment by ianthomas23** [comment]
It is supported in command line `find` where it does the somewhat counterintuitive find only within the supplied filename arguments. I've never had a real world use case for this. So one could argue that we should keep it for consistency with command line `find`, or we could simply disallow it because it is mostly useless?

**Comment by martindurant** [comment]
Let's get rid of it!
