### ISSUE TITLE
HTTP files read the wrong data when range requests aren't supported

### ISSUE THREAD

**Issue by takluyver** [fsspec/filesystem_spec#1140]
The description on #830 says:

> Does *not* allow random access from not the start of the download.

However, nothing appears to check for this, so it can return the wrong data. For example:

```python
import fsspec
url = 'http://piweb.ooirsn.uw.edu/das/data/Optasense/SouthCable/TransmitFiber/South-C1-LR-95km-P1kHz-GL50m-SP2m-FS200Hz_2021-11-01T16_09_15-0700/South-C1-LR-95km-P1kHz-GL50m-SP2m-FS200Hz_2021-11-01T231514Z.h5'

with fsspec.open(url) as f:
  f.seek(100)
  b = f.read(50)

print(b)
```

The data starts with `b'\x89HDF'`, the magic number at the start of an HDF5 file, instead of starting 100 bytes in. If range requests aren't supported, I'd expect `.read()` to error if you're not starting from 0.

This is somewhat complicated by the read-ahead caching - currently making multiple small reads (`[f.read(100), f.read(100)]`) does the right thing so long as the data is in the cache, but it will go wrong when it needs to fetch new data.

Ideally I guess it should use one of the streaming (non-seekable) file classes in this case, but I don't know if the `Accept-Ranges` header is used consistently enough that you can assume its absence means range requests won't work.

**Comment by martindurant** [comment]
>  If range requests aren't supported, I'd expect .read() to error if you're not starting from 0

I'm not aware of any general way to know this. Checking that the number of bytes received is the same as requested is not enough, since returning less is usually OK. I guess the return headers should include a Range keyword too?

**Comment by martindurant** [comment]
If the file is streaming, I would think h5py can't make use of it at all, no? The chance of the reads being made being in the right order is very small.

**Comment by martindurant** [comment]
> I think it should have status 206 (partial content) if it's responding with a range

I wouldn't bet on it. I have seen every variety of server response so far...

**Comment by takluyver** [comment]
OK, but the server behaviour here is valid AFAICT: it doesn't support range requests, never claims to, and it makes a standard response with a 200 code and all the content (or as much as we read before closing the connection). I'd argue that we should properly handle that case even if it makes things worse for some buggy servers. And if we're not sure about the returned data, I'd err on the side of throwing an error rather than returning (potentially) incorrect data.

I guess another option would be to reintroduce some variant of the BlockSizeError which #830 removed - if you ask for 100 bytes and it sends more, that sounds like a pretty good indicator that the range header was ignored.

**Comment by martindurant** [comment]
>  if you ask for 100 bytes and it sends more, that sounds like a pretty good indicator that the range header was ignored.

I think this is the best that we can do. Can it be done in such a way as to still allow read at the start of the file?

(What about cases where the server doesn't tell you how big the response will be? Read the whole thing first, and then error if there are too many bytes?)

> " a pretty good indicator"

Unfortunately, standards are not universally followed, so we only have indicators and heuristics, not defined behaviour.

**Comment by takluyver** [comment]
> I think this is the best that we can do. Can it be done in such a way as to still allow read at the start of the file?

I think so, yes - we can just allow it to go through if the start position is 0.

> What about cases where the server doesn't tell you how big the response will be? Read the whole thing first, and then error if there are too many bytes?

If the server responds with a 200 status rather than 206, and neither a `Content-Length` nor `Content-Range` header, it seems pretty unlikely to me that it's honouring a range request, so I'd just error at that point. We could download 5 MB of data (default block size) to check that, but I imagine it will often be a waste of time.

Maybe another compromise is to add a keyword arg like `http_range_supported=True` so the user can say that a misbehaving server does accept range requests, even if it looks like it doesn't. Passing `False` could also give you the streaming file API, so no seeking is allowed.

I can hopefully work on some of this tomorrow.

> Unfortunately, standards are not universally followed, so we only have indicators and heuristics, not defined behaviour.

Sure, I accept that. But I think we should prioritise the behaviour with servers that do follow the standards - including ignoring the range header - over those that don't.
