### ISSUE TITLE
ArrowFile: `seekable()` method

### ISSUE THREAD

**Issue by nyamashi** [fsspec/filesystem_spec#1153]
`ArrowFile.seekable()` seems  to always return `False` even setting `seekable=True` in  https://github.com/fsspec/filesystem_spec/blob/2022.11.0/fsspec/implementations/arrow.py#L152.

 I guess it should be added `"seekable"` in https://github.com/fsspec/filesystem_spec/blob/2022.11.0/fsspec/implementations/arrow.py#L196

```
import os
import fsspec

hdfs_url = 'hdfs://foo/bar/baz/'

fs, data_path = fsspec.core.url_to_fs(hdfs_url)

for p1, p2, p3 in fs.walk(data_path):
    if p3:
        for filename in p3:
            path = os.path.join(p1, filename)
            # print(path)
            f = fs.open(path, model="rb", seekable=True)
            print(f.seekable())
            break 
```
before
```
False
```

with `"seekable"` in https://github.com/fsspec/filesystem_spec/blob/2022.11.0/fsspec/implementations/arrow.py#L196
```
True
```

Could 'seekable' be added?

**Comment by martindurant** [comment]
Yes please!

**Comment by nyamashi** [comment]
@martindurant 
Thanks for your quick response. 😄 
I've added PR https://github.com/fsspec/filesystem_spec/pull/1154. 
Is that enough?
