### ISSUE TITLE
ArrowFSWrapper leaves protocol type as "abstract"

### ISSUE THREAD

**Issue by tdoehmen** [fsspec/filesystem_spec#1176]
First, thanks for the great work! I tried using the ArrowFSWrapper to register Arrow filesystems with DuckDB's fsspec integration (https://duckdb.org/docs/guides/python/filesystems) as it would be a really cool way to access HDFS from DuckDB.

However, there were two issues that I encountered, that I want to bring to your attention. (also see #1175)

The DuckDB fsspec integration uses the .protocol property of the fsspec filesystem to map filepaths to the correct filesystem. ArrowFSWrapped fsspec filysystems inherit the protocol type "abstract" from its base class, which leads DuckDB to assume that it is dealing with the abstract base class rather than a concrete implementation.

A workaround is to set the protocol type explicitly before passing it to DuckDB's .register_filesystem function:
```
hdfs_fsspec.protocol = "hdfs_arrow"
duckdb_con.register_filesystem(hdfs_fsspec)
duckdb_con.query("SELECT * FROM read_csv_auto("hdfs_arrow://test.csv")")
```

A nice solution in my eyes would be to be able to pass it to the ArrowFSWrapper constructor, and if builtin ArrowFSWrapped fsspec filesystems such as the HadoopFileSystem would have the .protocol property already set (e.g. "hdfs_arrow").

**Comment by martindurant** [comment]
You are right that ArrowFSWrapper should have a protocol set. Have you noticed, however, that there is a specific HadoopFileSystem too, which has protocol "hdfs"? It may be that this already does everything that you want.

I am not certain what the appropriate protocol for ArrowFSWrapper is, since it can also connect with S3 and local storage. Perhaps just "arrow"? 

In your example, where is test.csv actually?

**Comment by tdoehmen** [comment]
I was looking at this example in the Arrow documentation here (https://arrow.apache.org/docs/python/filesystems.html#using-arrow-filesystems-with-fsspec):

```
from pyarrow import fs
local = fs.LocalFileSystem()
from fsspec.implementations.arrow import ArrowFSWrapper
local_fsspec = ArrowFSWrapper(local)
print(local_fsspec.protocol )
#--> "abstract"
```

I think a simple solution would be to have a parameter in the ArrowFSWrapper.__init__() that lets one set the protocol name, like:
```
local_fsspec = ArrowFSWrapper(local, protocol="local")
print(local_fsspec.protocol)
#--> "local"
```

**Comment by martindurant** [comment]
pyarrow seems to provide `.type_name`, so how about
```diff
--- a/fsspec/implementations/arrow.py
+++ b/fsspec/implementations/arrow.py
@@ -53,6 +53,10 @@ class ArrowFSWrapper(AbstractFileSystem):
         self.fs = fs
         super().__init__(**kwargs)

+    @property
+    def protocol(self):
+        return self.fs.type_name
+
     @cached_property
```

May I ask why you want an arrow local file system rather than fsspec's own implementation?

**Comment by tdoehmen** [comment]
Ah great! Yes, I think that would be a cool solution.

Sure, the local fs would not be so interesting, it was just an example to demonstrate the original issue.
