### ISSUE TITLE
Bug report - AbstractAsyncStreamedFile - asynchronous writes are not working!  

### ISSUE THREAD

**Issue by vminfant** [fsspec/filesystem_spec#1204]
Hi, There seems to be a bug in `fsspec/asyn.py` - `AbstractAsyncStreamedFile`. 

I'm attempting to use `AbstractAsyncStreamedFile` to read/write data asynchronously but unfortunately i couldn't perform write operation as there seems to be a bug when calling `_upload_chunk` from `flush` method in `AbstractAsyncStreamedFile`. it doesn't seem to be awaiting. 

Error: 

```
RuntimeWarning: coroutine 'StreamFile._upload_chunk' was never awaited
  if self._upload_chunk(final=force) is not False:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Snippet highlighting the problem. 
```python
        if self._upload_chunk(final=force) is not False: 
            self.offset += self.buffer.seek(0, 2)
            self.buffer = io.BytesIO()
```
_upload_chunk should be awaited.  Could anyone please cross check this and let me know if this intentional for some reason. I'm happy to make a PR too!

**Comment by martindurant** [comment]
Please do make a PR, specifically with a test that touches this code.

**Comment by vminfant** [comment]
@martindurant, Sorry it took a while to get to this issue. I have fixed the bug and added some tests but I'm not able to push my code to the repo.

```ERROR: Permission to fsspec/filesystem_spec.git denied to vminfant.```

Is there any active push policy on this repo?

**Comment by martindurant** [comment]
You should for the repo (button in the extreme top right) to your account, and push a new branch there. github will give you a URL in the terminal for creating a PR, or you can visit your branch in your account and click the "compare and PR" green button.

Not only do repos generally want to keep the number of branches pared down, but CI workflows run from within a repo have access to repo secrets, so security policy limits who could in theory get access to them. I believe all OSS repos will be like this.

**Comment by vminfant** [comment]
Got it! I should have thought about this before raising it. PR #1217 can now be reviewed.
