### ISSUE TITLE
Documentation suggestion: Describe or at least link to URL / `fsspec.open` parameters for accessing data in different places

### ISSUE THREAD

**Issue by Cadair** [fsspec/filesystem_spec#1208]
I am trying to connect to a s3 compatible object store, and it's the first time I have tried to use fsspec.

I have just spent 5 minutes scouring the docs about how to construct a s3 url to a custom endpoint, and how to pass my authentication info etc. It's not until I opened GitHub to find this repo to open this issue that I noticed there is a `s3fs` repo with docs which look like they will answer my questions.

I suggest that in the `fsspec.open` (and probably other places) it's described that protocols can be registered (I assume that's what's happening here) and give people a way of discovering where to look for the protocols they are interested in.

Thanks!

**Comment by martindurant** [comment]
You were supposed to find your way to https://filesystem-spec.readthedocs.io/en/latest/api.html#other-known-implementations :|

Do you think such a pointer belongs in fsspec.open's docstring, or somewhere in the prose doc pages?

**Comment by Cadair** [comment]
yes I think so, mainly as a user I don't interact with those "other implementations" directly, I just type in a URL and it magically works for me. Also I would suggest that section has a little prose to explain that those "other implementations" register url prefixes and you should see them for arguments and url structure etc?

**Comment by martindurant** [comment]
cc @ianthomas23

**Comment by ianthomas23** [comment]
I intend to deal with this next week.
