### ISSUE TITLE
fsspec.generic.rsync fails with local -> GCSFileSystem

### ISSUE THREAD

**Issue by micahjsmith** [fsspec/filesystem_spec#1229]
As stated in title.

Yes, I see that `fsspec.generic` is experimental but would love to be able to use it!

Who is responsible for this error?
1. GCSFileSystem for not implementing `open_async`?
2. AsyncFileSystem for not fully implementing `open_async`?
3. GenericFileSystem for not checking the availability of `open_async` correctly in `_cp_file`?

Not sure what is the contract of `open_async` so I can't tell off the bat.

Clearly something is not implemented, if someone points me in right direction I'm happy to make a PR.

Thanks!

```
>>> import fsspec.generic
>>> src = "/tmp/foo"
>>> dst = "gs://my-bucket/foo"
>>> fsspec.generic.rsync(src, dst)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/micahsmith/.pyenv/versions/myvenv/lib/python3.9/site-packages/fsspec/generic.py", line 121, in rsync
    fs.cp(source_files, target_files, **kwargs)
  File "/Users/micahsmith/.pyenv/versions/myvenv/lib/python3.9/site-packages/fsspec/spec.py", line 1362, in cp
    return self.copy(path1, path2, **kwargs)
  File "/Users/micahsmith/.pyenv/versions/myvenv/lib/python3.9/site-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/micahsmith/.pyenv/versions/myvenv/lib/python3.9/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/Users/micahsmith/.pyenv/versions/myvenv/lib/python3.9/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/Users/micahsmith/.pyenv/versions/myvenv/lib/python3.9/site-packages/fsspec/asyn.py", line 358, in _copy
    raise ex
  File "/Users/micahsmith/.pyenv/versions/3.9.13/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/Users/micahsmith/.pyenv/versions/myvenv/lib/python3.9/site-packages/fsspec/generic.py", line 279, in _cp_file
    await fs2.open_async(url2, "wb")
  File "/Users/micahsmith/.pyenv/versions/myvenv/lib/python3.9/site-packages/fsspec/asyn.py", line 794, in open_async
    raise NotImplementedError
NotImplementedError

```

**Comment by martindurant** [comment]
There are two things:
- s3fs and gcsfs have not yet implemented open_async, although it would be pretty simple
- the check in _cp_file is not correct, it looks for the _open_async attribute, but this is always present for an async FS, raising NotImplemented if not overidden.

**Comment by micahjsmith** [comment]
@martindurant thanks for your response

> the check in _cp_file is not correct, it looks for the _open_async attribute, but this is always present for an async FS, raising NotImplemented if not overidden.

for this, would an appropriate fix in `fsspec.generic` be to try/catch the `NotImplementedError` instead of checking for the `_open_async` attribute?

**Comment by martindurant** [comment]
That is the simplest thing I can think of, yes.

**Comment by martindurant** [comment]
The following works for async, treaming reads in s3fs, but I cannot figure out how to do something similar for writes, except to copy the multipart-upload logic from S3File
```diff
--- a/s3fs/core.py
+++ b/s3fs/core.py
@@ -16,6 +16,7 @@ from fsspec.spec import AbstractBufferedFile
 from fsspec.utils import infer_storage_options, tokenize, setup_logging as setup_logger
 from fsspec.asyn import (
     AsyncFileSystem,
+    AbstractAsyncStreamedFile,
     sync,
     sync_wrapper,
     FSTimeoutError,
@@ -1944,6 +1945,11 @@ class S3FileSystem(AsyncFileSystem):

     invalidate_region_cache = sync_wrapper(_invalidate_region_cache)

+    async def open_async(self, path, mode="rb", **kwargs):
+        if "b" not in mode or kwargs.get("compression"):
+            raise ValueError
+        return S3AsyncStreamedFile(self, path, mode)
+

 class S3File(AbstractBufferedFile):
     """
@@ -2282,6 +2288,20 @@ class S3File(AbstractBufferedFile):
             )
             self.mpu = None

+class S3AsyncStreamedFile(AbstractAsyncStreamedFile):
+    def __init__(self, fs, path, mode):
+        self.fs = fs
+        self.path = path
+        self.mode = mode
+        self.r = None
+
+    async def read(self, length=-1):
+        if self.r is None:
+            bucket, key, gen = self.fs.split_path(self.path)
+            r = await self.fs._call_s3("get_object", Bucket=bucket, Key=key)
+            self.r = r["Body"]
+        return await self.r.read(length)
+
```

**Comment by okz** [comment]
I am not sure if `rsync` works with any cloud storage system, at all yet?  

I have been trying to get it do something with azure, and it's very fussy about authentication parameters, it did not know how to use sas_token's as credentials for example.

Closest I got was to provide the connection string with the account key, but it complains the destination is not a directory, but it is: 

```
fs = fsspec.filesystem("az", 
                       connection_string=f"DefaultEndpointsProtocol=https;AccountName={account_name};AccountKey={account_key};EndpointSuffix=core.windows.net"
                       )

rsync("file:///home/asd/", "az://test/output/", fs=fs)
```
```
ValueError: Can only rsync on a directory
```

Could anyone confirm if they were able to use rsync with a cloud storage system?

**Comment by martindurant** [comment]
@okz 

As you can see from the thread above, generic/rsync is more aspirational than complete. However, you should be able to use ABFS's `put` with `recursive=True` to the same effect. Help would be appreciated to get async writing working on all backends.

Having said that, the specific issue you see seems to be coming from a directory existence check, which is maybe not necessary and often problematic on blob storage.

**Comment by okz** [comment]
Thank you Martin,  I have moved on to recursive put.  Not as good, but can live with it.

Had got excited when I noticed rsync on the API, and had spent some time on it.  Wanted to make sure and document here it's not ready yet.  Not much comes out when `fsspec rsync` is searched. 

I wish I had time to help.

**Comment by SergiyShebotnov** [comment]
> @okz
> 
> As you can see from the thread above, generic/rsync is more aspirational than complete. However, you should be able to use ABFS's `put` with `recursive=True` to the same effect. Help would be appreciated to get async writing working on all backends.
> 
> Having said that, the specific issue you see seems to be coming from a directory existence check, which is maybe not necessary and often problematic on blob storage.

Just to make sure I understand, will using [The Azure Blob Filesystem](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-abfs-driver) work with GCS?

Not really sure how to do it, since with GCS we init fsscep with `fs = fsspec.filesystem("gcs")`

Any help is appreacted!

**Comment by martindurant** [comment]
It is a function not a method, fsspec.generic.rsync . Yes, it works with all known fsspec implementations.

**Comment by SergiyShebotnov** [comment]
> You should _not_ be passing `fs` here. The only kind of filesystem allowed is a GenericFileSystem
> 
> ```
> fs: GenericFileSystem|None
>     Instance to use if explicitly given. The instance defines how to
>     to make downstream file system instances from paths.
> ```

Thanks, it works! 
1. However using `recursive=True` sometimes produces "NotImplementedError". 
2. Secondly, adding a new file locally and running rsync does indeed copies the file to GCS bucket. However, and maybe I misunderstand rsync, if I delete a file locally, this file is not deleted on the GCS bucket. It was my understanding rsync would sync local files to the remote location (i.e. deleting locally, should delete remotely).

**Comment by martindurant** [comment]
> However using recursive=True sometimes produces "NotImplementedError".

rsync is always recursive, it works on a whole directory/tree

> if I delete a file locally, this file is not deleted on the GCS bucket

Use `delete_missing=True`

**Comment by martindurant** [comment]
If you would like to propose documentation to make this process clearer, I would much appreciate it.

**Comment by SergiyShebotnov** [comment]
> If you would like to propose documentation to make this process clearer, I would much appreciate it.

The `[documentation ](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.generic.rsync)`seems good, will look into more closely.
Thank you for prompt and precise replies!

**Comment by ryaminal** [comment]
I think this ticket should be closed so it doesn't confuse anyone. 

I was looking to use GCS with `fsspec.generic.rsync` and stumbled upon this ticket. almost didn't try it because this ticket indicated it "still" wasn't implemented yet.

But, can confirm that with `fsspec==2024.3.1` this works.

Also, love `fsspec` and appreciate all of the time and effort you all give to this project.

**Comment by martindurant** [comment]
Thank you!
