### ISSUE TITLE
Non-recursive directory copy incorrect

### ISSUE THREAD

**Issue by ianthomas23** [fsspec/filesystem_spec#1232]
A non-recursive directory copy, which is a slightly silly thing to attempt but is supported, gives the wrong result.

```python
cp("source/somedir/", "target/", recursive=False)
```

creates an empty directory `target/somedir`. But command-line `cp`, which is what we are basing our behaviour on, does nothing at all here.

**Comment by martindurant** [comment]
It's not _very_ wrong :)  In fact, with the trailing "/", it does look like "put the source item INTO the target", surprised that CLI cp is a no-op.

**Comment by ianthomas23** [comment]
Command-line copy gives you
```
$ cp source/subdir/ target/
cp: source/subdir/ is a directory (not copied).
```
regardless of trailing slashes on source or target.

I agree that it is not very wrong, ours feels like better behaviour really. But I would very much like to be able to say "we follow command-line copy behaviour" and not have a single exception to this.
