### ISSUE TITLE
Async put creates directories for you, sync put doesn't

### ISSUE THREAD

**Issue by MatthijsPiek** [fsspec/filesystem_spec#1258]
[Async put](https://github.com/fsspec/filesystem_spec/blob/4953f476944fdbae9e4e0c70930d77c7df2cdd85/fsspec/asyn.py#LL505C3-L505C3) creates a directory structure for you:
```
await asyncio.gather(*[self._makedirs(d, exist_ok=True) for d in rdirs])
```

[Sync put](https://github.com/fsspec/filesystem_spec/blob/4953f476944fdbae9e4e0c70930d77c7df2cdd85/fsspec/spec.py#L979) doesn't. 

It would be nice if that would be consistent. My personal preference would be creating directories.

**Comment by martindurant** [comment]
I think the sync put_file should create directories? Do you have a case in which it doesn't?
In the async case, it needs to be done ahead of time, otherwise you might have a race condition of each file trying to create all of its parent directories at once.

**Comment by MatthijsPiek** [comment]
```python
    def test_local_put_creates_directories(tmp_path, moto_s3_fixture):
        s3_fs: AbstractFileSystem = S3FileSystem()
        local_fs: AbstractFileSystem = LocalFileSystem()
    
        src_path = os.path.join(tmp_path, "a_file.txt")
    
        local_fs.touch(src_path)
    
        s3_dst_path = '/'.join([moto_s3_fixture, "sub1", "sub2", "a_file.txt"])
        local_dst_path = os.path.join(tmp_path, "sub1", "sub2", "a_file.txt")
    
        s3_fs.put(src_path, s3_dst_path)
        assert s3_fs.exists(s3_dst_path)
    
>       local_fs.put(src_path, local_dst_path)
```

Throws this exception:
```python
>           with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
E           FileNotFoundError: [Errno 2] No such file or directory: 
shutil.py:264: FileNotFoundError
```
As you can see: the same test succeeds on S3 (which uses the async implementation). I'd expect the two to be equivalent by default.

**Comment by ianthomas23** [comment]
You should be OK if you change
```python
    local_fs: AbstractFileSystem = LocalFileSystem()
```
to
```python
    local_fs: AbstractFileSystem = LocalFileSystem(auto_mkdir=True)
```
The default value for `auto_mkdir` is `False` (https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.local.LocalFileSystem) which is unfortunate.

Also, note that there have been quite a few changes recently to the `cp`, `get` and `put` behaviour, and this is neither finished nor fully consistent across the sync and async backends. This will be fixed in the next few weeks, for the next release.

**Comment by ianthomas23** [comment]
I am closing this as no further action is necessary.
