### ISSUE TITLE
Issues using fsspec.spec put method on version 2023.5.0

### ISSUE THREAD

**Issue by tiagocabo** [fsspec/filesystem_spec#1270]
I am using the fsspec version 2023.5.0 to try to upload a local file to a remote s3 bucket. I am having permission issues when the 
`self.isdir(lpath)` is executed. 

https://github.com/fsspec/filesystem_spec/blob/bbce5afb04ca98b52c7399bec4dc40cc50c9a738/fsspec/spec.py#L986
Before bumping to this version, both versions 2023.3.0 or 2023.4.0 were working fine. 

I think the issue is related with the `self.isdir`, because of the following error 

<img width="1093" alt="image" src="https://github.com/fsspec/filesystem_spec/assets/38300412/91d9eeea-699e-482f-bccc-1645dc0cf243">

also the `self.isdir` method points to a S3FileSystem 

<img width="678" alt="image" src="https://github.com/fsspec/filesystem_spec/assets/38300412/dd13e158-05ef-40df-909f-0676925cf55a">

**Comment by ianthomas23** [comment]
There is a fix for this in fsspec/filesystem_spec#1267.
