### ISSUE TITLE
Kwargs (such as overwrite=True) does not work with CachingFileSystem methods, such as open

### ISSUE THREAD

**Issue by SoptikHa2** [fsspec/filesystem_spec#1313]
I'm trying to use azure blob storage under the CachingFileSystem wrapper. However, I need to pass `overwrite=True` to the `open` call. Caching FS does not remember it and does not pass it to `az` filesystem when the cache is commited.

The minimal breaking example looks like this:

```py
# Run azurite
#
# docker-compose.yml:
#
# services:
#   blob_storage:
#     image: mcr.microsoft.com/azure-storage/azurite
#     command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
#     ports:
#       - 10000:10000
import fsspec

CONN_STRING = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"

fs = fsspec.filesystem("filecache", target_protocol="az", expiry_time=720,
     target_options={'connection_string': CONN_STRING})
#fs = fsspec.filesystem("az", connection_string=CONN_STRING)

fs.rm("test-container")
fs.mkdir("test-container") # ok

assert fs.ls("test-container") == [ ] # ok

with fs.open("test-container/foo", mode="wb") as file_handle:
    file_handle.write(b"foo") # ok

assert fs.ls("test-container") == [ "test-container/foo" ] # ok

# BREAKS: overwrite=True is ignored
with fs.open("test-container/foo", mode="wb", overwrite=True) as file_handle:
    file_handle.write(b"bar") # fails
```

I believe the root cause is the same as in #633.

I think, that the cause is that although `open` receives `overwrite=True` in `kwargs` [here](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/cached.py#L304), it does not propagate it further when cache is [commited](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/cached.py#L826).

**Comment by martindurant** [comment]
It sounds like you have the right solution here, to capture and pass on the kwargs at commit time. Would you like to make this a PR? To test, you can probably just us e a mock to see that the argument gets passed.

**Comment by SoptikHa2** [comment]
Yes, I just created a PR, thanks! Took me a (long) while to get to it, but I believe this should fix it.
