### ISSUE TITLE
What does cache_check do?

### ISSUE THREAD

**Issue by RoelantStegmann** [fsspec/filesystem_spec#1317]
Could someone explain a bit better what this parameter does?

        cache_check: int
            Number of seconds between reload of cache metadata 

I looked at the code, but it seems to reload the local cache data? What would happen if I put this to infinity?

**Comment by martindurant** [comment]
This is in place in case another process is using the same cache, so the contents could change at any time. If you are using the cache only from one process at a time, it should be fine to set it to a large number.

**Comment by ianthomas23** [comment]
Closing this as no action is required.
