### ISSUE TITLE
Was `DFReferenceFileSystem` removed from fsspec?

### ISSUE THREAD

**Issue by norlandrhagen** [fsspec/filesystem_spec#1331]
Hi there, 

I'm trying to use Kerchunk to create parquet references. In this [section of the Kerchunk docs](https://fsspec.github.io/kerchunk/advanced.html?highlight=dfreferencefilesystem#parquet-storage), `DFReferenceFileSystem` is imported from `fsspec`. 

When working off the main fsspec & Kerchunk branches I get:

`AttributeError: module 'fsspec.implementations.reference' has no attribute 'DFReferenceFileSystem'`

Just wondering if this was removed and if there was an updated method + exmaple for opening up the parquet reference with Kerchunk.

```
fs = fsspec.implementations.reference.DFReferenceFileSystem(
    "combined.parq", lazy=True)
```

Kerchunk version: `'0.1.2+9.g72c5d50'`
fsspec version: `'2023.6.0+17.g2aa7589'`

**Comment by martindurant** [comment]
The main ReferenceFileSystem also handles parquet now, DFReferenceFileSystem got merged into it

**Comment by norlandrhagen** [comment]
Great! Thanks for the info. I can update the Kerchunk docs if you like.

**Comment by martindurant** [comment]
Yes, please!

Note that the the new system is writable. The most convenient way to manage creating and saving new references is to instantiate `LazyReferenceMapper` and pass it as the `fo` argument to `ReferenceFileSystem`. All of this could do with "advanced" level documentation.

**Comment by ianthomas23** [comment]
I am closing this as the example is now corrected in the kerchunk docs.
