### ISSUE TITLE
Sorted paths in expand_path produces bad mapping between source and destination files

### ISSUE THREAD

**Issue by john-jam** [fsspec/filesystem_spec#1347]
When using lists as source and destination, the mapping between the two during copy/get/put operations is not accurate.

For example:
```python
from fsspec.implementations.memory import MemoryFileSystem
from hashlib import md5

def get_hash(value: str) -> str:
    return md5(value.encode("utf-8")).hexdigest()

fs = MemoryFileSystem()

paths_from = []
paths_to = []
for i in range(10):
    hashed_i = get_hash(value=str(i))
    path_from = f"in/{hashed_i}.txt"
    path_to = f"out/{hashed_i}.txt"
    fs.pipe(path=path_from, value=f"{i}".encode("utf-8"))
    paths_from.append(path_from)
    paths_to.append(path_to)

fs.copy(path1=paths_from, path2=paths_to)

for i in range(10):
    hashed_i = get_hash(value=str(i))
    file_content = fs.cat(f"out/{hashed_i}.txt").decode("utf-8")
    if file_content != str(i):
        print(f"file content {file_content} | expected {str(i)}")
```

This code outputs:
```bash
file content 6 | expected 0
file content 9 | expected 1
file content 7 | expected 2
file content 4 | expected 3
file content 1 | expected 4
file content 2 | expected 5
file content 8 | expected 6
file content 0 | expected 7
file content 5 | expected 8
file content 3 | expected 9
```

This is because the `path1` list gets sorted in the `expand_path` method but the `path2` remains the original one. So we can't expect an accurate mapping when calling copy/get/put operations like this: 
```python
fs.copy(
    path1=["in/myfile1", "in/myfile2"],
    path2=["out/myfile1", "out/myfile2"],
)
```

If it's an expected behavior, please let me know how to do batch copy when we want to control the destination path of each file.
If not, I think I can create a PR this week end.

**Comment by martindurant** [comment]
You are right, this is incorrect behaviour.

Maybe expand_path should not sort when given an explicit list, or we need some other way to cope with ordering the list for the destination.

**Comment by john-jam** [comment]
> Maybe expand_path should not sort when given an explicit list, or we need some other way to cope with ordering the list for the destination.

I don't think the destination ordering would be best here because it assumes that we'll chose the same paths/names for source and destination and examples like that won't work as expected:

```python
fs.copy(
    path1=["in/myfile1", "in/myfile2"],
    path2=["out/myfile9", "out/myfile8"],
)
```

I like the idea of completely avoiding sorting when an explicit list is given but I'm not sure if removing sets and [bitwise operations](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/spec.py#L1139) in the `expand_path` method would not lower performances too much (only on really huge lists though).

My first question then is if that would be acceptable to use lists instead of sets in `expand_path` to keep the order of the source files?

If not, then we have to consider several use cases:
1. The source is a list but the destination is a string
2. The source is a list and the destination is a list
3. The source is a string and the destination is a string

We only care about source files order in `2` because in `3`, no lists are involved and in `1`, the destination names will be defined from the source names (not important if source is sorted or not).

But also, in case of `2`, we actually don't need to call `expand_path` at all because if source and destination are lists, we shouldn't provide source paths like `myfolder/my*file.*` or expect any recursive or maxdepth options to be handled so no need to call `expand_paths`.

My second question is if it would be ok to add a condition to call `expand_paths` in `get/put/copy` only if we are in `1` and `3` case?

**Comment by martindurant** [comment]
> But also, in case of 2, we actually don't need to call expand_path at all because if source and destination are lists, we shouldn't provide source paths like myfolder/my*file.* or expect any recursive or maxdepth options to be handled so no need to call expand_path.

> My second question is if it would be ok to add a condition to call expand_path in get/put/copy only if we are in 1 and 3 case?


Yes, this is exactly the conclusion I came to too.

**Comment by john-jam** [comment]
Added a fix [here](https://github.com/fsspec/filesystem_spec/pull/1349).

Do you think this could be included in the next release?
