### ISSUE TITLE
Different behaviour for `fs.get` for `fsspec>2023.1.0`

### ISSUE THREAD

**Issue by toby-coleman** [fsspec/filesystem_spec#1348]
I'm trying to understand different behaviour I get between `fsspec<=2023.1.0` compared with later versions.

This is my code
```python
import fsspec
import tempfile

print(fsspec.__version__)

lfs = fsspec.filesystem("file")

lfs.touch(path="/tmp/data/a.txt")
lfs.touch(path="/tmp/data/b/a.txt")

with tempfile.TemporaryDirectory(prefix="tt") as path:
    lfs.get(rpath="/tmp/data", lpath=path, recursive=True)
    print(lfs.ls(path=path))
```

On `fsspec==2023.1.0` I get the following output:
```
2023.1.0
['/var/folders/7c/0cjr9j7j50l2qg_kpcslzyd40000gn/T/tt8kr16c40/a.txt', '/var/folders/7c/0cjr9j7j50l2qg_kpcslzyd40000gn/T/tt8kr16c40/b']
```

On `fsspec==2023.6.0` I get:
```
2023.6.0
['/var/folders/7c/0cjr9j7j50l2qg_kpcslzyd40000gn/T/ttrql5966f/data']
```

The newer versions of `fsspec` copy the `data` folder, whereas older versions copy the contents of `data`.

--
OS: MacOS 13.5
Python version 3.9

**Comment by martindurant** [comment]
Perhaps https://filesystem-spec.readthedocs.io/en/latest/copying.html helps? It attempts to clarify the expected behaviour of the various operations in different situations.

**Comment by toby-coleman** [comment]
Thanks @martindurant - according to 1(e) Directory to existing directory, the adding a trailing `"/"` to `rpath` indicates that the contents of the `data` folder should be copied.  The behaviour in the newer versions of `fsspec` is therefore correct.

New code:
```python
import fsspec
import tempfile

print(fsspec.__version__)

lfs = fsspec.filesystem("file")

lfs.touch(path="/tmp/data/a.txt")
lfs.touch(path="/tmp/data/b/a.txt")

with tempfile.TemporaryDirectory(prefix="tt") as path:
    lfs.get(rpath="/tmp/data/", lpath=path, recursive=True). # Trailing / added
    print(lfs.ls(path=path))
```

Outputs as expected:
```
['/var/folders/7c/0cjr9j7j50l2qg_kpcslzyd40000gn/T/tt2kxwlit9/a.txt', '/var/folders/7c/0cjr9j7j50l2qg_kpcslzyd40000gn/T/tt2kxwlit9/b']
```

**Comment by martindurant** [comment]
So OK to close this?

**Comment by toby-coleman** [comment]
Yes, thank you.  Closing.
