### ISSUE TITLE
AbstractFileSystem.protocol `list[str]` error in reference filesystem

### ISSUE THREAD

**Issue by ap--** [fsspec/filesystem_spec#1395]
Hello,

I encountered the following error when using the reference filesystem and providing an s3 filesystem via the `fs` kwarg:

```pycon
>>> import fsspec
>>> fs_remote = fsspec.filesystem("s3", anon=True)
>>> fs_ref = fsspec.filesystem("reference", fo={}, fs=fs_remote)
Traceback (most recent call last):
  File "[...]/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 4, in <module>
  File "/Users/andreaspoehlmann/Development/filesystem_spec/fsspec/registry.py", line 290, in filesystem
    return cls(**storage_options)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andreaspoehlmann/Development/filesystem_spec/fsspec/spec.py", line 79, in __call__
    obj = super().__call__(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andreaspoehlmann/Development/filesystem_spec/fsspec/implementations/reference.py", line 630, in __init__
    self.fss[remote_protocol] = fs
    ~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
```

This crashes because `S3FileSystem.protocol = ['s3', 's3a']` is a `list` instead of a tuple. I checked all filesystems in fsspec and the fsspec org, and s3fs is the only one using `list[str]`. All others are `tuple[str, ...] | str`.

#### possible fixes

There are 3 occurrences of "protocol-sequence unpacking" code in fsspec. The reference filesystem one is the only one not checking for `list[str]` as protocol.

https://github.com/fsspec/filesystem_spec/blob/6aa8a9a888f8d7ce2c721f6896f1ffabde84ef05/fsspec/implementations/reference.py#L625-L630

https://github.com/fsspec/filesystem_spec/blob/6aa8a9a888f8d7ce2c721f6896f1ffabde84ef05/fsspec/spec.py#L1408-L1412

https://github.com/fsspec/filesystem_spec/blob/6aa8a9a888f8d7ce2c721f6896f1ffabde84ef05/fsspec/implementations/cached.py#L148-L152

The issue could be fixed by either making `s3fs.S3FileSystem.protocol` a tuple, or by checking for list in the reference filesystem too.

<br>

I can prepare a PR for the preferred solution.

Cheers,
Andreas

**Comment by martindurant** [comment]
I believe we should standardise on `tuple`, is makes no sense for this attribute to be mutable.

**Comment by ap--** [comment]
That sounds good! I created a PR in `s3fs` 😃
