### ISSUE TITLE
Missing sub-directories when listing root in `ReferenceFileSystem`

### ISSUE THREAD

**Issue by Kirill888** [fsspec/filesystem_spec#1430]
## Minimal reproduction

```python
import fsspec
from fsspec.implementations.reference import ReferenceFileSystem

print(f"fsspec: {fsspec.__version__}")
fs = ReferenceFileSystem({"a": "A", "B/C/b": "B", "B/C/d": "d", "B/_": "_"})
print(fs.ls(""))
```

Produces following output

```
fsspec: 2023.9.2
[{'name': 'a', 'type': 'file', 'size': 1}]
```

notice missing directory `B/` directory at top level. If we move `B/_` ahead of `B/C/b`, error does not occur. Problem is here

https://github.com/fsspec/filesystem_spec/blob/1637a97aa53f04ff0e71cfb44ef54c24d7586eca/fsspec/implementations/reference.py#L989-L999

**Comment by martindurant** [comment]
I see how the intermediate directory gets skipped. Do you have an edit that would make this behave right? You have provided a very nice test that can go straight in.

**Comment by Kirill888** [comment]
yep, made a PR
