### ISSUE TITLE
Request to create a new fsspec endpoint / repo - alluxiofs

### ISSUE THREAD

**Issue by LuQQiu** [fsspec/filesystem_spec#1442]
Hi fsspec team, thanks for the great product that significantly offloads the storage connection overhead for applications. 

We are developing the Alluxio & fsspec integrations to help leverage Alluxio's distributed caching capability to improve the remote storage data access of compute framework including but not limited to Ray, PyTorch, Hugging face, Presto, and Spark.

Could fsspec maintainers help create a new repository named "fsspec/alluxiofs" so that our team from Alluxio could continuously develop the integration and contribute to the ecosystem?

Background info:

The open-source project [Alluxio](https://github.com/Alluxio/alluxio) is a distributed caching storage that bridges the gap between compute frameworks and storage systems and i am the PMC maintainer of Alluxio.

We had a alluxiofs prototype available at  https://github.com/LuQQiu/alluxiofs and it has been tested against Ray
```
# Import fsspec & alluxio fsspec implementation
import fsspec
from alluxiofs import AlluxioFileSystem

# Overwrite S3 fsspec implementation to Alluxio fsspec implementation
fsspec.register_implementation("s3", AlluxioFileSystem, clobber=True)

# Create Alluxio filesystem
alluxio = fsspec.filesystem("s3", etcd_host=args.etcd_host)

# Ray read data from Alluxio using S3 URL
ds = ray.data.read_images("s3://ai-ref-arch/imagenet-full/train", filesystem=alluxio)
```
which significantly improves the ray data loading performance. We will publish the Ray and Alluxio fsspec integration blog soon.

In the future, we want to explore the possibility of developing a cache interface in fsspec to leverage external storage systems as a distributed key-value caching layer on top of the numerous storage interfaces fsspec has.

**Comment by LuQQiu** [comment]
Hi @martindurant, Thank you for your valuable input!

We have identified two potential methods to integrate Alluxio with fsspec, and would want to hear your thoughts:

1. Unified Namespace Approach (alluxio:///):
`alluxio:///` namespace can combine multiple storage systems into a single file system hierarchy. For example, the namespace can look like
```
/      represents storage 1: e.g. s3://alluxio-root-bucket/
- /folderA    represents s3://alluxio-root-bucket/folderA
- - /folderA/file1     represents s3://alluxio-root-bucket/folderA/file1
- - /folderA/file2    represents s3://alluxio-root-bucket/folderA/file2
-/folderB      can mount another dataset s3://alluxio-sub-bucket/
- - /folderA/file1    represents s3://alluxio-sub-bucket/file1
- - /folderA/file2   represents s3://alluxio-sub-bucket/file2
```
2. Original URLs:
Our users prefer to access datasets while enjoying the distributed cache benefits via original URLs (e.g., s3://user_bucket/path/to/dataset). This approach is preferred due to its simplicity and familiarity, requiring no changes to existing training or analytics scripts.

Given these insights, I propose supporting both approaches:

1. fsspec/alluxiofs Repository:
This would specifically serve the alluxio:/// namespace, with optional functionality to override some storage systems, like S3.
Alluxio is responsible for interfacing with the storage systems with Alluxio built-in storage connectors and managing data retrieval.
2. Alluxio as a Super Caching Layer:
- Considering the end-user preference for original URLs, could we position Alluxio primarily as a caching layer on top of fsspec?
- When users are reading a file, it will contact Alluxio to ask for data availability. If cache hits, Alluxio serves the data. If cache miss, fsspec will fetch data from fsspec filesystem (e.g. s3fs) and put it into Alluxio. 
- Probably a simple read_page, write_page interface is enough and Alluxio can be an implementation variance of that.

Look forward to your thoughts!

**Comment by LuQQiu** [comment]
We did more investigation into fsspec repo and thanks for the great examples!
Good to use the "alluxio" protocol, and support the caching function by allowing

- System-level caching for all target protocols
- - my_fs = fsspec.filesystem(“alluxio”, target_protocol=’s3’, target_options={‘anon’:True}, alluxio options)
- File-level caching
- - my_file = fsspec.open("alluxio::s3://bucket/key",
                 s3={'anon': True}, alluxio={alluxio options})

**Comment by martindurant** [comment]
Sounds great. Let me know if you want to transfer the repo and/or include the protocol in the list of "known" ones in the fsspec docs.

**Comment by LuQQiu** [comment]
@martindurant 
We modified the protocol to be "alluxio" and the code is available at https://github.com/LuQQiu/alluxiofs main branch. Could you help transfer the repo?
Now I am working on creating a PR to filesystem_spec repo to adding the protocol and docs
Thanks in advance

**Comment by LuQQiu** [comment]
The first version is 
- read from alluxio cache in list status, get path info, read (fetch_range) calls
- fallback to target protocol for all other operations

Some internal code changes are needed to support cache from target protocol and we are working on that part.
So that in the future

- list status, get path info, read (fetch_range) calls
- will check if cache exists in Alluxio, if not, cache from target protocol

**Comment by martindurant** [comment]
> Could you help transfer the repo?

I believe you have to initiate this in the "secure" area of the repo settings. I have added you as an org member, if that makes a difference.

**Comment by martindurant** [comment]
(actually, it's called "Danger Zone", and is at the bottom of the General page in repo settings)

**Comment by LuQQiu** [comment]
Thanks @martindurant !
I clicked "Danger Zone" and "Transfer Ownership", and encountered "you don’t have the permission to create public repositories on fsspec"

**Comment by LuQQiu** [comment]
<img width="968" alt="Screen Shot 2023-12-26 at 10 29 26 AM" src="https://github.com/fsspec/filesystem_spec/assets/25273483/d73678b2-8952-457b-bc31-d45a1a4810c7">

**Comment by martindurant** [comment]
Can you invite me as admin/owner on your repo? I'm not sure that's possible; else, you can transfer it to me, and I'll move it up.

**Comment by LuQQiu** [comment]
@martindurant Could not find the admin/owner field (although they do have a collaborator field with weird permission models), so i directly initiated the transfer ownership to you, thanks for helping

**Comment by martindurant** [comment]
Now at https://github.com/fsspec/alluxiofs , and you should be admin.

**Comment by LuQQiu** [comment]
That's awesome! Appreciate your help @martindurant !

**Comment by martindurant** [comment]
I will close this issue, as the protocol was merged in, and we can continue the conversation in your repo if need be
