### ISSUE TITLE
glob("*") still not returning any matches with ZipFileSystem

### ISSUE THREAD

**Issue by olemke** [fsspec/filesystem_spec#1448]
PR #1445 did not fix the problem described in #1443.

The testcase provided in #1443 still does not return any matches with 2023.12.1:

```
➜ python zipglob.py
[]
{'date': '2023-12-05T10:09:44-0500', 'dirty': False, 'error': None, 'full-revisionid': 'b6536bef07abe21d4eecdc690048c30b523c20f7', 'version': '2023.12.1'}
```

**Comment by martindurant** [comment]
Is the [test case](https://github.com/fsspec/filesystem_spec/pull/1445/files#diff-f25abadbfc3c919e06d23e2ae346e670d1ae289a1f22154bdb2ed7289a5cf650R88) added in the PR not essentially the same?

**Comment by olemke** [comment]
No worries, come back to it when you have the time. I'll just stick with 2023.10.0 for now.

**Comment by martindurant** [comment]
Python ZipFile only added mkdir() in 3.11 https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.mkdir :(
