### ISSUE TITLE
How to write large files to a ZipFileSystem using fsspec

### ISSUE THREAD

**Issue by jenshnielsen** [fsspec/filesystem_spec#1474]
Consider the following example

```python
# %%
from fsspec.implementations.zip import ZipFileSystem
import zipfile
import numpy as np

small_array = np.random.rand(1000)
with open("small.npz", "wb") as f:
    np.save(f, small_array)

large_array = np.random.rand((int(4e8)))
with open("large.npz", "wb") as f:
    np.save(f, large_array)

with open("./large.npz", "rb") as f:
    large_data = f.read()

with open("./small.npz", "rb") as f:
    small_data = f.read()

# create empty zip file
with zipfile.ZipFile("./test.zip", "w"):
    pass

zfs = ZipFileSystem("./test.zip", "w")

with zfs.open("small_array", "wb") as f:
    f.write(small_data)

with zfs.open("large_array", "wb") as f:
    f.write(large_data)
zfs.close()

```
Here writing large array would fail but writing small array would work as expected. 
 
As the implementation ZipFileSystem is based on the zipfile std lib module I had a look in [the documentation of that module](https://docs.python.org/3/library/zipfile.html). 

As you can see from that to write a file larger than the 32bit limit to a zip archive one must either 

pass `force_zip64=True` to `zipfile.open` or pass a `ZipInfo` object as the first argument to open. 
As far as I can see neither is possible since the open implementation in ZipFileSystem does not take kwargs and forward them to the underlying open method and the logic within ZipFileSystem is written to assume that the first argument is a str.

**Comment by martindurant** [comment]
Yes you are right; I had assumed that opening the zipfile with 64bit support would be enough, but no. With `open()` we don't know how big the file will be (even if it only get a single call to `write()`), so we either have to pass an argument or just assume 64bit every time (if support is on). Is there any downside to always assuming?

**Comment by jenshnielsen** [comment]
Thanks, The only issue I could see would be to read the file on a 32bit system, not sure how common that would be today. Perhaps it makes sense to also set the force flag to true if the allow flag is true?

**Comment by martindurant** [comment]
> Perhaps it makes sense to also set the force flag to true if the allow flag is true?

Yes, let's do that.
