### ISSUE TITLE
`fsspec.open()` doesn't work with square brackets in a filename

### ISSUE THREAD

**Issue by anmyachev** [fsspec/filesystem_spec#1476]
For example, `fsspec.open("filename[test].csv")`.

Is this by design or a bug? (python builtin `open` function works in this case, at least for python 3.11)

**Comment by martindurant** [comment]
fsspec.open uses the same code path as open_files, and allows glob patterns in the string. These are not generally used in filepaths.... So in this case, the `[test]` is interpreted as a range of possible characters, but only one. 
Interestingly, the following does work:
```
fsspec.open("filename*.csv")
```

There is probably a way to escape the special characters, but we are laying glob on regex, so I'm not sure how. Also, passing a list containing just the one match (with open_files) doesn't work either, since fsspec also considers a list of glob-strings.

**Comment by anmyachev** [comment]
@martindurant thanks for the quick answer!

> fsspec.open uses the same code path as open_files, and allows glob patterns in the string. These are not generally used in filepaths...

Indeed, this is rare. Then I assume the current implementation will remain as is?

> There is probably a way to escape the special characters, but we are laying glob on regex, so I'm not sure how. 

Unfortunately me too.

**Comment by martindurant** [comment]
I'd be happy to find a way through, especially since open() is supposed to work on single paths, never return a list.

**Comment by Skylion007** [comment]
@martindurant Doesn't `re.escape` do everything you want here?

**Comment by martindurant** [comment]
@Skylion007 , you can try, but we are converting from glob-strings to re, and [..] is valid wildcarding in both.

**Comment by Skylion007** [comment]
@martindurant Do we actually want to support globbing in this code path, seems to odd to me to want to do that. Easy solution seems to be use [glob.escape](https://docs.python.org/3/library/glob.html#glob.escape) and `re.escape` if we want to match both filenames literally, right? Or at least we can add a flag to do so?

It seems to me like this codepath is designed to work the same as builtins.open so we should probably match call convention. Also, it's not listed anywhere in the doc that `open` is suppose to support globs https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.open

**Comment by martindurant** [comment]
True, but at the moment, open() calls open_files(...)[0], and the latter does support globbing. It is not totally unreasonable to want to open("file*") and get back the first file that matches, although this is not explicitly documented.

**Comment by martindurant** [comment]
Besides which, I am not sure that the escaped character would not be caught by the contains_magic checks anyway; and don't forget that they would need to be *un*-escaped again before passing to the actual backend.

**Comment by Skylion007** [comment]
But it's also totally reasonable to want to get `file[final].csv`. Currently there is not a way to access this type of filename at all though... It also prevents fsspec open from otherwise being a nearly perfect replacement of builtins.open() so that you can just monkeypatch it in.

**Comment by Skylion007** [comment]
@martindurant Figured it out! It was a bug in an arg not being respected in `open_files`
