### ISSUE TITLE
`LocalFileSystem.ls()` does not work on filenames

### ISSUE THREAD

**Issue by nicholasjng** [fsspec/filesystem_spec#1478]
Repro:

```
fs = LocalFileSystem()

fs.touch("a.json")
fs.ls("a.json")
```

I expected this to return a single-entry list with the stat object for `a.json`, but instead it raises a `NotADirectoryError` because `os.scandir()` does not allow file-like inputs:

https://github.com/fsspec/filesystem_spec/blob/069e107fa056166fd4e7db75e909ebac85f372fd/fsspec/implementations/local.py#L63-L64

In contrast, a subsequent `ls -la a.json` behaves as expected, showing the single file stat result.

**Comment by martindurant** [comment]
I am aware of this. At the same time, some people have asked that ls should only list directories and not return single files (in other implementations)... We definitely want consistency, and I would tend towards yes, returning the single file.

**Comment by nicholasjng** [comment]
Good to know. If it's of interest, my use is to query an rpath and decide whether it's a single file or multiple files, i.e. a directory. I do however want to support the "is a directory with a single file in it" and "is an empty directory" edge cases, otherwise I would fall back to `fs.info()`.

FWIW, I'm looking for something that is consistent across as many implementations as possible - so I'd like to avoid things like `fs.isdir()` and the like.

**Comment by martindurant** [comment]
Why is `isdir()` problematic?

**Comment by nicholasjng** [comment]
Heh, because of my internal prejudice. I had saved it in my mind as "might not be implemented if the storage does not support directories", but I forgot it runs through `info`. I'll use that then and see how far I get. 

Is there still interest in changing the `LocalFileSystem.ls()` behavior? I would send in a patch in that case.

**Comment by martindurant** [comment]
> Is there still interest in changing the LocalFileSystem.ls() behavior?

yes, please
