### ISSUE TITLE
Unable to Configure Hadoop FileSystem Replication Argument

### ISSUE THREAD

**Issue by samssh** [fsspec/filesystem_spec#1485]
**Hi everyone,**

**I'd like to report an issue with the `replication` argument in PyArrow's Hadoop FileSystem implementation.**

**The problem:**

- The default `replication` value of 3 in PyArrow overrides the value set in the HDFS site file, preventing external configuration.
- This can lead to incorrect replication factors, storage usage issues, and failures in clusters with a replication factor of 2.

**Proposed solution:**

- Add the `replication` argument to the constructor of the `HadoopFileSystem` class with a default value (e.g., 3).
    - This would allow users to explicitly set the replication factor when creating a new FileSystem object.

**I'm happy to provide more details, code, or error messages as needed. Please let me know if there's any specific information that would be helpful.**

I'm eager to contribute and writing the pull request.

**Comment by martindurant** [comment]
This sounds like a reasonable request. I'd be happy to see the code implications in a PR.
