### ISSUE TITLE
FTPFileSystem.ls fails if server returns leading "total x" in directory listing 

### ISSUE THREAD

**Issue by Bizarious** [fsspec/filesystem_spec#1489]
Hello,

I'm trying to get files from an ftp server that does not support mlsd. The filesystem then uses the `dir()` method to retrieve the directory listing. It then fails as the ftp server returns a leading "total x" which seems not expected, judging from the implementation I have seen in `_mlsd2()`.

This seems to be an issue with fsspec, as this case seems to be quite common: 

"When decoding, it is important to note that many implementations include a line at the start like "total <number>".  Clients should ignore any lines that don't match the described format." - https://files.stairways.com/other/ftp-list-specs-info.txt

**Comment by martindurant** [comment]
Unfortunately, the FTP server used for testing is somewhat capable, so we don't see this issue in CI. It could be emulated with mocking. FTP servers are pretty poorly standardised, generally...

It would indeed be good to add verification and the ability to cope with various kinds of server response in `ls()`. Would you like to add code to cope with the partiicular situation you are facing?

**Comment by Bizarious** [comment]
Thank you for your answer. Yes, I can implement a fix. I will submit a pull request this or next week, if that is suitable for you.

**Comment by martindurant** [comment]
Yes, thanks.
