### ISSUE TITLE
infer_compression type using file signatures?

### ISSUE THREAD

**Issue by exitflynn** [fsspec/filesystem_spec#1543]
Right now, when a compression type is to be inferred, the [`utils.infer_compression()`](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/utils.py#L141-L151) function does so by looking at the file extension, for example if a gzipped file is named in the filename.gz format. However since this condition isn't a necessity for gzipped files, this approach misses those gzipped files which do not end with the .gz extension.

Could using [file signatures // 'magic bytes'](https://en.wikipedia.org/wiki/List_of_file_signatures) to infer be a better idea for the project?

**Comment by martindurant** [comment]
This is actually something that's done by `intake.recommend`, (specifically `intake.readers.datatypes.recommend`) if you want to give it a try.

**Comment by exitflynn** [comment]
thanks @martindurant, that's exactly what I was talking about. I wanted to make sure and clarify if there's some sort of 'go-ahead' on this cause in that case I'd love to contribute! (I'd totally understand if not, but just wanted to make sure i wasn't misinterpreting anything!)

**Comment by martindurant** [comment]
I am not entirely sure how to make this fit in with the project - normally we open the file (with or without compression) only much later. So I wouldn't recommend using "infer" to look for magic bytes, but something more explicit ("analyse"?). I would be happy to see such code; but first, are you sure Intake does not meet your needs in this regard?

**Comment by exitflynn** [comment]
sorry about the late response but yes Intake definitely meets those needs. 
I was mostly just thinking about something like this out of curiosity 😅, thanks for the response!
