### ISSUE TITLE
fs.rm(filename, recursive=True) fails with a strange error

### ISSUE THREAD

**Issue by ghislainp** [fsspec/filesystem_spec#1557]
I get this strange error below when deleting a directory using fs.rm, because "out" is None at line 2006 in core.py although the function  _run_coros_in_chunks is supposed to return a list in any case (through I'm unexperienced with async/await)

  File "(...)/python3.11/site-packages/s3fs/core.py", line 2006, in _rm
    return sum(out, [])
           ^^^^^^^^^^^^
TypeError: can only concatenate list (not "NoneType") to list

The directory is supposed to be deleted (on s3) but is not deleted, and when I call fs.exists the directory after the deletion, it is said to be absent, although it is not, so I guess there is an error somewhere behind the scene.

The problem occurs when using Prefect which seems to use async and other complex machinery for the concurreny. When I try to call fs.rm manually on the same directory, everything works fine. 

I'm using version 2024.3 but I've had this problem for a few months and with previous version as well.

**Comment by ghislainp** [comment]
I suspect the error comes from a return statement without returned value. It should return an empty list: return []
This does not explain why my directory is not deleted but at least that would not generate an error.

 ```python

   async def _bulk_delete(self, pathlist, **kwargs):
        """                                                                                        
        Remove multiple keys with one call                                                         
                                                                                                   
        Parameters                                                                                 
        ----------                                                                                 
        pathlist : list(str)                                                                       
            The keys to remove, must all be in the same bucket.                                    
            Must have 0 < len <= 1000                                                              
        """
        if not pathlist:
            return               # <------------------------ should be: return []

```

**Comment by martindurant** [comment]
Sound like you are quite right, please make a PR to fix the return. It nay well be that the files have indeed been deleted, but the dircache has not been cleared following the error.

**Comment by ghislainp** [comment]
I was mislead by the error message. In fact out=[None] after the await _run_coros_in_chunks call and sum([None], []) return can only concatenate list (not "NoneType") to list. 

And indeed
```python
sum([None], [])  # raise an error: TypeError: can only concatenate list (not "NoneType") to list

[None]+[]   # work like a charm
```

Isn't it weird ?

**Comment by ghislainp** [comment]
Sorry to re-open this issue but I think this is really an error.  The line sum(out, []) is correct  only if out is a list of list, but out coming from fsspec.asyn._run_coros_in_chunks seems not to be a list of list. It is initialized as results=[None]*n in fsspec.asyn._run_coros_in_chunks. I'm not sure it is changed to a list of list.

In   _bulk_delete , which is called by run_coros_chunks for fs.rm, I can see this comment which I interpret as  Exception are not raised...  and the consequence is that result=[None]*n is return which then cause the sum(out, []) problem
# TODO: we report on successes but don't raise on any errors, effectively                            
        #  on_error="omit"  

Is it possible to raise the error ? I'd like to see the error in my case

**Comment by martindurant** [comment]
`_run_coros_in_chunks` returns a list of results, where each result is the output of one coroutine passed in. In the case of s3fs's rm, each of those calls is itself a _batch_ of files to delete, so in this case, uniquely, the output should be a list of lists, and so should be flattened to get the list of deleted paths.

**Comment by martindurant** [comment]
> Is it possible to raise the error

With some effort... It would involve scanning the Error part of the response
https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html#API_DeleteObjects_ResponseSyntax

**Comment by martindurant** [comment]
@ghislainp , if you intend to work on that, please let me know.
