### ISSUE TITLE
Installing via pip installs an outdated gcsfs package 

### ISSUE THREAD

**Issue by mbanani** [fsspec/filesystem_spec#1603]
Hi! Thanks for the great package. I noticed that the most recent install results in downgrading the gcsfs package to 0.8.0. 

Steps to reproduce:  `pip install "fsspec[gcs,s3]>=2024.3.1"` which results in `Successfully installed fsspec-2024.5.0 gcsfs-0.8.0 s3fs-2024.5.0 ujson-5.10.0`

**Comment by martindurant** [comment]
gcsfs 2024.5.0 is now on pypi after a few hours' lag. You are good to go.
