### ISSUE TITLE
is there any way to copy from WebHDFS files to another WebHDFS?

### ISSUE THREAD

**Issue by aiqwe** [fsspec/filesystem_spec#1654]
Hello 😃,
Is there any way to copy from one WebHDFS to another?

I tried to find methods relevant to spec, WebHDFS, etc., but I couldn't 😢.
Or do I have to implement that function myself?

**Comment by martindurant** [comment]
fsspec.generic.rsync is what you will want, but you will have to style one of your urls as "webhdfs://" and the other as something else. Even so, the copies happen *locally*, fsspec can't farm your job out over your HDFS cluster (but maybe dask can).

If you are only diong one or two files, you can also do it manually:

```python
fs1 = fsspec.filesystem("webhdfs", ...)
fs2 = fsspec.filesystem("webhdfs", ....)
with fs1.open(origin, "rb") as f1:
    with fs2.open(destination, "wb") as f2:
        block = f1.read(blocksize)
        while block:
            f2.write(block)
            block = f1.read(block)
```

**Comment by aiqwe** [comment]
oh, ty! 😁

If implement with parallel methods, it's ok the copies happen locally.

ty again! 👍
