### ISSUE TITLE
feat: leveraging OpenDAL for more sources of/performant Data Access Layer

### ISSUE THREAD

**Issue by wey-gu** [fsspec/filesystem_spec#1655]
ref: https://github.com/apache/opendal

updated: it's already [planned by OpenDAL community](https://github.com/apache/opendal/issues/4511)!

**Comment by martindurant** [comment]
Implementation will appear at fsspec/opendalfs

**Comment by Xuanwo** [comment]
Thank you @martindurant to make it happen!
