### ISSUE TITLE
Feature request: Databricks Files API

### ISSUE THREAD

**Issue by yuanhao-li** [fsspec/filesystem_spec#1656]
Databricks Files API: https://docs.databricks.com/api/workspace/files

The old [DBFS](https://github.com/fsspec/filesystem_spec/issues/495) API is not compatible with Databricks Unity Catalog. Unity Catalog is the governance layer which secures access to the data. It would be nice to bring the new Files API into the fsspec lib, which is compatible with UC.

**Comment by martindurant** [comment]
I'm afraid I don't know too much about this technology (looks like another HTTP REST service) - could you sketch out how they all fit together, please?

**Comment by martindurant** [comment]
Ping @yuanhao-li , can you help to further specify the scope here? It would also be very useful to know if there is an emulator for the storage API, so that any fsspec implementation can be properly tested.

**Comment by yuanhao-li** [comment]
@martindurant  Hi Martin, sorry for my quick ticket. I have just checked the [PR](https://github.com/fsspec/filesystem_spec/pull/504/files#diff-0f5c723a6926aa4d6e4fe1996f4ec94077f8437428fabb215bf9352fd8c4d99e) for supporting DBFS API. Currently it's not possible to use Files API to implement fsspec. 

Feel free to close  this ticket. I will keep you updated if there're some API changes come from Databricks.

**Comment by yuanhao-li** [comment]
> > it's not possible to use Files API to implement fsspec
> 
> What do you think is missing?

I couldn't find the APIs in new Files API to support streaming like:
* create
* close
* add-block
* read

**Comment by martindurant** [comment]
OK, so the only way to write a file is one-shot (no multi-part upload). That means caching in memory or on local disk, which is not fatal. The download endpoint doesn't say if it supports Range headers.

**Comment by sugibuchi** [comment]
Hi. I recently started working on this topic [sugibuchi/fsspec-databricks](https://github.com/sugibuchi/fsspec-databricks).

The multipart upload is not yet officially supported, but there is an undocumented API for this. I backported the code that uses this undocumented API in the Databricks SDK for Python to a new fsspec implementation.

**Comment by martindurant** [comment]
@sugibuchi - let us know! If you reach feature parity and beyond with the built-in version, we could decide to switch where the protocol dispatches to. Of course, we'd like to get some testers using it first.
