### ISSUE TITLE
AttributeError: '_pygit2.Blob' object has no attribute 'hex'

### ISSUE THREAD

**Issue by mxmlnkn** [fsspec/filesystem_spec#1702]
```python3
import fsspec
f = fsspec.open("git://tests/")
print(f.fs.ls("/"))
```

Results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/fsspec/implementations/git.py", line 93, in ls
    "hex": obj.hex,
AttributeError: '_pygit2.Blob' object has no attribute 'hex'
```

After downgrading with: `python3 -m pip install --user --force-reinstall 'pygit2==1.14`, it works again. It seems that the API break occurred in 1.15. Seems like they don't follow semantic versioning.

This dependency version requirement should be added to the pyproject.toml, or worked around.

**Comment by martindurant** [comment]
Do you happen to know what the new attribute is called?

**Comment by mxmlnkn** [comment]
The [changelog](https://github.com/libgit2/pygit2/blob/master/CHANGELOG.md#1150-2024-05-18) states:

> Remove deprecated object.hex, use str(object.id)
