### ISSUE TITLE
Ask transfer tosfs to the fsspec official org

### ISSUE THREAD

**Issue by yanghua** [fsspec/filesystem_spec#1726]
Hi community:

I am the contributor of [tosfs](https://github.com/volcengine/tosfs), which is an implementation of fsspec. I filed this issue to ask if we can transfer it to the fsspec official org.

Now I would like to introduce tosfs briefly.

Tosfs is an SDK that implements fsspec and aims to provide a convenient Python filesystem interface for [TOS（Tinder Object Storage）](https://www.volcengine.com/docs/6349/74820). By the way, TOS is the object store service of the volcano engine(Cloud as a Service Provider owned by [ByteDance](https://www.bytedance.com/en/)).

If any question or guidance need to be followed please let me know.

Thanks,
Vino

**Comment by martindurant** [comment]
Please remind me on Monday, when I'll have more time to look into it. Is tosfs mentioned in the fsspec "known implementations" docs?

**Comment by yanghua** [comment]
>> Please remind me on Monday, when I'll have more time to look into it.

Ok.

>> Is tosfs mentioned in the fsspec "known implementations" docs?

No, it hasn't been added to "known implementations", I will add it.

**Comment by yanghua** [comment]
The doc pr is here #1728

**Comment by yanghua** [comment]
@martindurant Following your suggestion, ping you @martindurant on Monday.

**Comment by yanghua** [comment]
Hi @martindurant I have sent the admin permission invitation. thanks~

**Comment by yanghua** [comment]
@martindurant , thanks, close this issue.
