### ISSUE TITLE
get_fs_token_paths swallows url with cached protocol

### ISSUE THREAD

**Issue by groutr** [fsspec/filesystem_spec#1727]
blockcache and cached refer to the same class in the registry, however I observe the following.

```python
url = 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/prod/nwm.20241016/forcing_analysis_assim/nwm.t00z.analysis_assim.forcing.tm00.conus.nc'
z1 = fsspec.open(f"blockcache::{url}")
# <OpenFile 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/prod/nwm.20241016/forcing_analysis_assim/nwm.t00z.analysis_assim.forcing.tm00.conus.nc'>
z2 = fsspec.open(f"cached::{url}")
# <OpenFile ''>
```
It appears the path goes missing when open calls `get_fs_token_paths`
```python
fsspec.core.get_fs_token_paths(f"blockcache::{url}")   # returns correct path
fsspec.core.get_fs_token_paths(f"cached::{url}")   # returns empty string for path
```
Should the behavior be consistent here?

**Comment by groutr** [comment]
My guess is that it happens here: https://github.com/fsspec/filesystem_spec/blob/master/fsspec/core.py#L354-L358

**Comment by martindurant** [comment]
You are quite right. There may well not be a good reason to keep the "cached" name around, although any better way to encode these special cases would be appreciated.

**Comment by groutr** [comment]
@martindurant Coincidentally, all of the caches inherit from CachingFileSystem, so one possible solution could be:

```python
if issubclass(cls, CachingFileSystem) and 'target_protocol' not in kw:
    bit = previous_bit
```
But this might just be another band-aid. I'm unsure if CachingFileSystem is meant to be a base class for caching file systems.

**Comment by martindurant** [comment]
> might just be another band-aid

Seems like a slightly better one than the current one.
