### ISSUE TITLE
LazyReference: Passing options to `.open`  of the reference file

### ISSUE THREAD

**Issue by wachsylon** [fsspec/filesystem_spec#1746]
I created references with kerchunk. Because of missing storage space, I was thinking of just compressing the files which are referenced with `lz4`. My question is: Could I leave the references as is and just pass the `compress="infer"` option somewhere in the reference file system so that it is used for opening the referenced file? I guess it would make sense to cache the uncompressed referenced files so that they can be reused if multiple chunks are in one reference file. Does that work somehow?

If this is not feasable, could we kerchunk files that are compressed with `lz4`  oder `zstandard` similar to zip and tar? afai understood, cat ranges is also possible on the parquet zstandard compressed tables.

If both approaches are possible, what would you recommend?

**Comment by wachsylon** [comment]
btw, i tried to pass this option with
```
cd={"compression": "infer"}
fs = fsspec.filesystem(
    "reference", 
    fo="test.parq", 
    target_options=cd, 
    remote_options=cd,
    storage_options=cd,
    **cd
)
```
but none of these settings make a difference. i added a `print` for the `kwargs` in the `cat_ranges` [function](https://filesystem-spec.readthedocs.io/en/stable/_modules/fsspec/spec.html#AbstractFileSystem.cat_ranges) and the dict is empty.

**Comment by wachsylon** [comment]
I think there is a missunderstanding. I try to be more clear:
Originally:
File1 <- reference-table
Anywhere in the reference file system when accessing the data throug references:
`fs.open(File1)`

After compression:
File1Compr <- reference table

where file1compr has the same name and the same chunks after decompressing it.

Why can't I pass option to the `fs.open`? Like
`fs.open(file1,**kwargs)`

**Comment by martindurant** [comment]
The question is, is this parquet? If yes, I don't think there's a code path to add arguments to open(); but, again, I am doubtful that compression gains you much for this case.

**Comment by wachsylon** [comment]
Parquet or json should not be relevant to my issue. It is about the files that are *referenced* **inside** the jsons or parquets in the `path`column. I gain storage space if I compress these referenced files.

I thought I have to specify `remote_options` to pass sth to the `fs` that is used to work with the files. But it seems like these options are not passed correctly.

One related thing that I find suspicious is that there are functions that accept `**kwargs` and which call again functions that accept `**kwargs` but do not pass them when calling them. E.g.:

https://github.com/fsspec/filesystem_spec/blob/9a161714f0bbfe44ee769f259420f2f7db975471/fsspec/spec.py#L836

**Comment by wachsylon** [comment]
thanks for the explanation! Since my files are netcdf and Grib, I discard the idea for now. But thanks!
