### ISSUE TITLE
Minimal python version

### ISSUE THREAD

**Issue by cmp0xff** [fsspec/filesystem_spec#1754]
In https://github.com/fsspec/filesystem_spec/blob/master/pyproject.toml, minimal python version is 3.8.

In https://github.com/fsspec/filesystem_spec/blob/master/.github/workflows/main.yaml, however, only versions >= 3.9 are tested.

**Comment by martindurant** [comment]
Yes. py3.8 is no longer maintained, so it will be dropped from our support too, but fsspec does still work there.
