### ISSUE TITLE
Setup CI for Windows

### ISSUE THREAD

**Issue by dhirschfeld** [fsspec/filesystem_spec#235]
It appears that CI only runs on linux? It would be good to also test against Windows to ensure no bugs or posix-isms pass unnoticed.

Perhaps also move to GH Actions?

**Comment by martindurant** [comment]
Certainly should, and I bet we'll find a bundle of problems (although some local file functionality is clearly not designed for win, and should be marked as such).

**Comment by dhirschfeld** [comment]
I'll close under the assumption this is fixed by #239

**Comment by martindurant** [comment]
No, this still needs to be done - I fixed in the sense that everything passed on my windows system, now that I have one.
