### ISSUE TITLE
tar backend?

### ISSUE THREAD

**Issue by martindurant** [fsspec/filesystem_spec#297]
A TAR file is like a file-system in that it contains directories and files. These are simply concatenated end-to-end, with short headers, but after a single pass of the file, the whole set of files and their offsets can be known (and maybe stored somewhere). Indeed, since each header contains the size of the file, you can skip the data bits altogether on this pass.

*However*, tar files are often stored compressed (gz, bz2), so to seek to a particular location to read a contained file amounts to scanning through all the compressed file up to that point. Any tar backend would only work well with uncompressed files.

cc @kmpaul

**Comment by martindurant** [comment]
This is as opposed to ZIP files, which are compressed file-wise and contain an index, so that each file can be accessed immediately.

**Comment by kmpaul** [comment]
@martindurant Thanks for starting this!  I think this would be interesting to explore.  I think you are correct that a compressed tarball would not work efficiently; you would need to uncompress it before you could use it as a filesystem.

**Comment by martindurant** [comment]
> you would need to uncompress it before you could use it as a filesystem

ideally uncompress it as you are receiving it and store the expanded version!

**Comment by kmpaul** [comment]
> ideally uncompress it as you are receiving it and store the expanded version!

Yes!  Indeed that would be nicer.  That might be a good default, especially since most compressed tarballs have "double compression" (i.e., compression of the tarball containing compressed files), meaning that the expansion of the compressed tarball shouldn't take up too much more space than the original.

**Comment by martindurant** [comment]
Indexing:
```
tf = tarfile.TarFile('file.tar')
out = {ti.get_info()['name']:  (ti.get_info(), ti.offset_data) for ti in tf}
```
(I assume python's tar is smart enough here to seek past the data segments).

**Comment by kmpaul** [comment]
@martindurant Should I just start putting together a draft PR for this?

**Comment by martindurant** [comment]
If you have the time, that would be great. It is up to you whether you make a way to persist the file contents index.
Note that the input to `TarFile` can be a file-like object, so this can work on remote TAR files too, except that random-access would be slow (but maybe good enough).

**Comment by kmpaul** [comment]
Ok.  I may have to start this next week, but I'll put together a draft PR.

**Comment by kmpaul** [comment]
Oooh!  Thanks, @martindurant!

**Comment by zklaus** [comment]
I think this issue has been addressed and can be closed, no?

**Comment by martindurant** [comment]
Yes, closing.
As an interesting side-note: ReferenceFileSystem can provide an index into a TAR, allowing for parallel/async read access even on remote archives (so long as you store the references somewhere).
