### ISSUE TITLE
test_runtildone fails with RuntimeError

### ISSUE THREAD

**Issue by QuLogic** [fsspec/filesystem_spec#452]
I've tried to run this on Fedora 31 (Python 3.7), all the way to Rawhide (Python 3.9), and this test does not work on any of them. The result is:
```pytb
_______________________________ test_runtildone ________________________________

    @pytest.mark.skipif(sys.version_info < (3, 7), reason="Async fails on py36")
    def test_runtildone():
>       loop = asyncio.get_event_loop()

fsspec/tests/test_async.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <asyncio.unix_events._UnixDefaultEventLoopPolicy object at 0x7f5ee4231d50>

    def get_event_loop(self):
        """Get the event loop for the current context.
    
        Returns an instance of EventLoop or raises an exception.
        """
        if (self._local._loop is None and
                not self._local._set_called and
                isinstance(threading.current_thread(), threading._MainThread)):
            self.set_event_loop(self.new_event_loop())
    
        if self._local._loop is None:
            raise RuntimeError('There is no current event loop in thread %r.'
>                              % threading.current_thread().name)
E           RuntimeError: There is no current event loop in thread 'MainThread'.

/usr/lib64/python3.7/asyncio/events.py:644: RuntimeError
```

**Comment by martindurant** [comment]
Hm, these tests pass elsewhere, and the [doc](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) clearly says that `get_event_loop` should create a loop, if one does not yet exist. The caveat reads:

> If there is no current event loop set in the current OS thread, the OS thread is main, and set_event_loop() has not yet been called

so maybe for some reason some part of this is violated in your setup?

**Comment by QuLogic** [comment]
Note that in 3.10 that behaviour was deprecated:

> Deprecated since version 3.10: Deprecation warning is emitted if there is no running event loop. In future Python releases, this function will be an alias of [get_running_loop()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop).

**Comment by QuLogic** [comment]
But more importantly, the test was deleted, so no need to keep this open.
