### ISSUE TITLE
python 3.6+ warning

### ISSUE THREAD

**Issue by vidstige** [fsspec/filesystem_spec#612]
When running with python 3.6+ I'm getting the following warning from pytest. It sounds like something that should be easy to alleviate.

```
venv/lib/python3.7/site-packages/fsspec/__init__.py:47
  /home/vidstige/src/volumental-vaka/venv/lib/python3.7/site-packages/fsspec/__init__.py:47: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
    for spec in entry_points.get("fsspec.specs", []):
```

**Comment by martindurant** [comment]
You see this only via pytest?

**Comment by martindurant** [comment]
Note that, for the moment, we still support py36 too, so we cannot change the call here unless it works on all versions?

**Comment by vidstige** [comment]
Yeah, only via pytest. But I'm guessing all tools that looks at the DeprecationWarning will report it.

**Comment by vidstige** [comment]
Backwards compatibility is important. I'll see if there is a way to fix it while still working on py36. Is that the oldest version you're supporting in master right now?

**Comment by martindurant** [comment]
Correct, and it will likely be dropped on the timescale of months.

**Comment by efiop** [comment]
Already trying to use select if available: https://github.com/fsspec/filesystem_spec/blob/00b812378461efc8ac273914a359ed4fdb1beb94/fsspec/__init__.py#L50 .
