### ISSUE TITLE
SMB Protocol support for storage_options

### ISSUE THREAD

**Issue by mattinbits** [fsspec/filesystem_spec#704]
When using `fsspec` with the `smb` protocol, e.g. `with fsspec.open("smb://myserver/share/file.txt") as f:` it does not seem to be possible to pass storage options to the underlying `smbprotocol` library.

The implementation calls `smbclient.open_file` via `_open` here: https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/smb.py#L202

This method on `smbclient` supports options such as `share_access`: https://github.com/jborean93/smbprotocol/blob/master/smbclient/_os.py#L311

However, although `_open` in `smb.py` passes `kwargs` to `smbclient.open_file`, the `kwargs` are not propagated from the outer call to `fsspec.open` https://github.com/intake/filesystem_spec/blob/master/fsspec/core.py#L102 

Is there an established pattern for passing these implementation-specific options through to the `_open` call in the implementation? Should the implementation capture them in the constructor of `SMBFileSystem` since the `storage_options` appear to be passed when an instance of `AbstractFileSystem` is instantiated here? https://github.com/intake/filesystem_spec/blob/master/fsspec/core.py#L376

**Comment by martindurant** [comment]
Yes, you are quite right: the "storage options" in `fsspec.open` refer to global parameters used in creating the file-system, and do not fo to its file-open method. We could reasonably add another optional argument to `fsspec.open` specifically for this purpose. Note that most versions of `_open()` don't take any/many options.

The trouble that will need to be faced, is that `fsspec.open` can create multiple file systems in the case of a chained URL. It can already pass arguments to the various components, but whether and where `_open` will be called isn't clear or consistent (e.g., zip operates on one open file, but simplecache uses get() to download files and never uses open at all). Maybe the extra argument in `fsspec.open` would always only go to the "outermost" `_open`.

> Should the implementation capture them in the constructor

This is the only way to do it now

**Comment by mattinbits** [comment]
Thank you for the rapid response!

> This is the only way to do it now

I will have a go at a PR on this basis.
