### ISSUE TITLE
FileNotFoundError [LocalFileSystem] on unix-like root / directory 

### ISSUE THREAD

**Issue by e-roux** [fsspec/filesystem_spec#829]
Hello,

in case of `LocalFileSystem().ls('/')`, a `FileNotFoundError` is being raised. 

```python
FileNotFoundError: [Errno 2] No such file or directory: ''
```

This looks quite normal as path is stripped right 
https://github.com/fsspec/filesystem_spec/blob/b68be6c57f54a71c6ffc89e669c410da353ebc1f/fsspec/implementations/local.py#L54

Is this an expected behavior?

**Comment by martindurant** [comment]
In `LocalFileSystem._strip_protocol`, we have `rstrip("/")`, where the slash character is commonly used to denote a directory path, but is not actually part of the path name. A special case could be made for the root path (as is already done in `_parent`).

**Comment by e-roux** [comment]
It would make sense to include a special check for the root directory, or defaulting to root directory in case of Exception with such an error with empty directory. I can make a PR if needed.

**Comment by martindurant** [comment]
Please do!
