### ISSUE TITLE
Can HTTPFileSystem use a different session implementation?

### ISSUE THREAD

**Issue by betolink** [fsspec/filesystem_spec#836]
Looks like aiohttp is the only supported way to create HTTP sessions, would it be possible to use `requests` for this? I'm working on opening files that require authentication with a [redirect outside the original domain.](https://github.com/aio-libs/aiohttp/issues/5783) I know how to implement a workaround using `requests` that requires re-implementing how the auth headers are handled after the redirect (subclassing and overriding a method) but `aiohttp` [forbids this](https://github.com/aio-libs/aiohttp/blob/e021d5e7b897afd807032f4d441fcabf813d7fcc/aiohttp/client.py#L288) =(.

If this could be enabled it would transform this

```python
fs = fsspec.filesystem('https',
                       client_kwargs = {'auth': aiohttp.BasicAuth('user', 'password'),
                       'allow_redirects': True})
```
into something like 

```python
fs = fsspec.filesystem('https', cls=requests.Session, 
                                client_kwargs = {'auth': requests.BasicAuth('user', 'password'),
                                                 'allow_redirects': True})
# or
fs = fsspec.filesystem('https', cls=aiohttp.ClientSession,
                                client_kwargs = {'auth': aiohttp.BasicAuth('user', 'password'),
                                                 'allow_redirects': True})
```

I'm sure there are many considerations that I'm probably not aware and this may not be trivial or even possible.

**Comment by martindurant** [comment]
I'm afraid the HTTPFileSystem implementation i s fundamentally asynchronous, and it would not be able to work with a blocking API like `requests`. If someone wished, it a new, synchronous, implementation could be written (or copied from old versions of this package), but I don't believe there is a strong demand for this.

**Comment by betolink** [comment]
It makes sense, I guess I could override the instance method or do some subclassing trick to avoid loosing the Auth headers on CORS redirect =)
