### ISSUE TITLE
How to add gcp credentials json?

### ISSUE THREAD

**Issue by DanTaranis** [fsspec/filesystem_spec#850]
Hi, 
I'd like to use this to fetch files in secure buckets. How can I do that? does fsspec automatically deal with permissions in some way?
I assume I'm not the only user with a private bucket.

**Comment by martindurant** [comment]
The documentation you want is here: https://gcsfs.readthedocs.io/en/latest/#credentials  I hope it covers everything you need.

**Comment by DanTaranis** [comment]
awesome! thanks so much for the super fast reply - this was exactly what I was looking for. 

out of curiosity - does this work in some way with pathlib's Path ?

**Comment by martindurant** [comment]
Not by itself, but see [universal_pathlib](https://github.com/fsspec/universal_pathlib), which is a mostly complete implementation of Path for fsspec.

**Comment by DanTaranis** [comment]
I found [this](https://towardsdatascience.com/transparentpath-a-python-package-to-manage-paths-on-google-cloud-storage-ae25a15a44d5). It worked better for me on GCS.

**Comment by martindurant** [comment]
OK, up to you of course.
