### ISSUE TITLE
distutils is deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [fsspec/filesystem_spec#879]
https://www.python.org/dev/peps/pep-0632/#migration-advice

https://github.com/fsspec/filesystem_spec/blob/0417b3484964b9c3a72fe2b680f9edb52ef0def1/fsspec/implementations/tests/test_local.py#L12

https://github.com/fsspec/filesystem_spec/blob/bd932c30f6998532002885aa0b98a1ed6f18bd14/fsspec/spec.py#L7

**Comment by isidentical** [comment]
It seems like we use it here:
https://github.com/fsspec/filesystem_spec/blob/bd932c30f6998532002885aa0b98a1ed6f18bd14/fsspec/spec.py#L91-L101

I don't know whether that part of the code is still needed though, it seems like a temporary hack. CC: @martindurant

**Comment by martindurant** [comment]
Pyarrow < 2 ( https://pypi.org/project/pyarrow/#history ) would be about a year and a half old, should we just drop it, then? I vote yes.

**Comment by isidentical** [comment]
👍🏻

**Comment by isidentical** [comment]
We still use it in the tests @martindurant.

**Comment by isidentical** [comment]
https://github.com/fsspec/filesystem_spec/blob/0417b3484964b9c3a72fe2b680f9edb52ef0def1/fsspec/implementations/tests/test_local.py#L349-L362

**Comment by martindurant** [comment]
I'm not too worried about deprecation in a test, but I can fix that too. This test became obsolete anyway.
