### ISSUE TITLE
Add smb to implementations in docs

### ISSUE THREAD

**Issue by rdmolony** [fsspec/filesystem_spec#886]
Hi there,  it seems [`smb`](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/smb.py) is missing from [the implementations API reference](https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations).  I'm happy to give this a go on Saturday morning unless you want to resolve this more quickly 

---

btw I've just used `smb` to connect to a remote Windows filesystem, very happy right now, thanks!

**Comment by martindurant** [comment]
Please do submit a PR

**Comment by rdmolony** [comment]
Right so I looked at `docs/source/api.rst` & it appears that 72e08c4 adds the required code to `Built-in Implementations`, this was committed in 2020-07-02 & the latest [readthedocs build](https://readthedocs.org/projects/filesystem-spec/builds/) is ~2 months ago.  I'm not sure why the current implementation isn't working

**Comment by martindurant** [comment]
Ah, I see the docs were not triggered automatically. I triggered it manually right now, and next week can investigate why it didn't do by itself.
