### ISSUE TITLE
Add py310 tests, drop py37?

### ISSUE THREAD

**Issue by martindurant** [fsspec/filesystem_spec#912]
For discussion.

**Comment by isidentical** [comment]
+1 to 3.10, but for the 3.7 I guess it makes sense to wait the EOL which is `27 Jun 2023` (one and a half year from now).

**Comment by martindurant** [comment]
OK for 3.7, unless it starts to cost us effort.

**Comment by isidentical** [comment]
Agreed.

**Comment by ianthomas23** [comment]
Adding `py310` and removing `py37` occurred in PR #996 so this can be closed.
