### ISSUE TITLE
fs.ls("/") raises error after fs.rm("/", recursive=True) for memory filesystem

### ISSUE THREAD

**Issue by benlindsay** [fsspec/filesystem_spec#925]
To replicate this error, run this:

```python
import fsspec

fs = fsspec.filesystem("memory")
fs.rm("/", recursive=True)
fs.ls("/")
```

Which results in the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../site-packages/fsspec/implementations/memory.py", line 91, in ls
    raise FileNotFoundError(path)
FileNotFoundError
```
I would expect it to return an empty list as it does before the `ls.rm()` call.

**Comment by martindurant** [comment]
Good point, there is an implicit root directory in `pseudo_dirs` that the `rm` will have deleted, but we should enforce that it is always present.

**Comment by martindurant** [comment]
Since you cannot delete "/" (or ""), should it raise to attempt to do so, or silently ignore removing the root?

**Comment by benlindsay** [comment]
I'm leaning towards silently ignoring removing the root, but open to whatever makes the most sense. My thought is that in a real filesystem, if you do `rm -rf /`, I would theoretically expect the root directory to still be there after that's all done, although I don't intend to actually try it 😅. Also, if we think about how this would apply in a `DirFileSystem` context, if, say, we have a `DirFileSystem` representing an S3 bucket, I think the `DirFileSystem` shouldn't be able to reach outside of that directory, so removing `"/"` should just remove the contents of the bucket, not the bucket itself. Thoughts?
