### ISSUE TITLE
Issue running tests_http in a ipv6 host

### ISSUE THREAD

**Issue by eamanu** [fsspec/filesystem_spec#927]
Hi,

During the build of fsspec package for Debian, some tests (http) fail in a host without 
routable v4:

```
server = 'http://localhost:9898'

    def test_list(server):
        h = fsspec.filesystem("http")
        out = h.glob(server + "/index/*")
>       assert out == [server + "/index/realfile"]
E       AssertionError: assert [] == ['http://loca...dex/realfile']
E         Right contains one more item: 'http://localhost:9898/index/realfile'
E         Use -v to get the full diff

fsspec/implementations/tests/test_http.py:164: AssertionError
----------------------------- Captured stderr call -----------------------------
2022-03-12 13:16:10,147 - fsspec.http - DEBUG - _ls_real -- http://localhost:9898/index/
2022-03-12 13:16:10,151 - fsspec.http - DEBUG - _exists -- http://localhost:9898/index/
------------------------------ Captured log call -------------------------------
DEBUG    fsspec.http:http.py:147 http://localhost:9898/index/
DEBUG    fsspec.http:http.py:301 http://localhost:9898/index/

```
More detail in [0].

[0] https://buildd.debian.org/status/fetch.php?pkg=fsspec&arch=all&ver=2022.02.0-1&stamp=1647091024&raw=0

**Comment by martindurant** [comment]
Thanks for posting. Is there any way to run an HTTP server in such a situation? Is there a way to detect that this is the case and skip the tests?

**Comment by eamanu** [comment]
HI @martindurant, sorry for the delay. I can try to patch the tests to detect ipv6 config, and then try to run the test server with that configuration. That's you mean?

**Comment by eamanu** [comment]
Hi @martindurant,

In Debian this patch was applied [0].

[0] https://sources.debian.org/src/fsspec/2022.5.0-1/debian/patches/0001-explicit-use-of-127.0.0.1.patch/

**Comment by martindurant** [comment]
Would you like to put that patch into a PR here? I'd be happy to accept it. I wonder (slightly) if there might be any cases where that address doesn't work.
