### ISSUE TITLE
'LocalFileOpener' object is not iterable for Win11

### ISSUE THREAD

**Issue by wqh17101** [fsspec/filesystem_spec#928]
code to reproduce
```
import fsspec

file_path = r"./test.csv"
file = fsspec.open(file_path).open()

for line in file:
    print(line)
```
got
```
TypeError: 'LocalFileOpener' object is not iterable
```
![image](https://user-images.githubusercontent.com/26429138/159825725-a329829e-e85b-40fc-8603-29f2a3eddc1a.png)

related issues https://github.com/modin-project/modin/issues/4298

**Comment by wqh17101** [comment]
@martindurant Maybe ? Win10 can work too for me.

**Comment by martindurant** [comment]
Are you willing to test on win10?

**Comment by wqh17101** [comment]
@martindurant I tested on win10. It worked well.

**Comment by timsnyder** [comment]
Looks like MS has downloadable Win11 virtual machine images for development and testing https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by martindurant** [comment]
Thanks for reminding me, I had forgotten about this. Downloading win11 now.

**Comment by martindurant** [comment]
Sorry, I find that it works fine in win11 too!

**Comment by wqh17101** [comment]
v0.7.4 not work
v2022.5.0 work now

**Comment by martindurant** [comment]
I don't know why, but glad it works now! 0.7.4 was quite a while ago.
