### ISSUE TITLE
Wrong file separator returned by fs.sep under Windows

### ISSUE THREAD

**Issue by gmaze** [fsspec/filesystem_spec#937]
When running CI tests for argopy under Windows OS, 
it seems that the file separator returned by a fsspec local file system (with `fs.sep`) is not the `\`

I've made a specific Github Action to illustrate this, one run make this issue visible at:
https://github.com/euroargodev/argopy/runs/5784702001?check_suite_focus=true#step:8:9

Basically it says:
```bash
Run python -c "import fsspec; print(fsspec.__version__, ':', fsspec.filesystem('file').sep)"
2022.02.0 : /
```
with the Operating system being Microsoft Windows Server 2022

Am I missing something here about the filesystem .sep property ? or am I right to expect `\` to be returned ?

**Comment by martindurant** [comment]
>  am I right to expect \ to be returned ?

No: we use posix style paths even on windows internally. If you pass a windows-style path to any of the functions of LocalFileSystem, the first thing that happens is that _strip_protocol turns it into posix. We *used* to allow a windows separator here, but found ti too hard to work with.

**Comment by gmaze** [comment]
ok, so If I want to make sure my own internal use of fsspec is correct, I should also make use of:
https://github.com/fsspec/filesystem_spec/blob/21a03a0a4dfdc7c820bbb75bbe848c833b51d6aa/fsspec/implementations/local.py#L200

**Comment by martindurant** [comment]
Yes, I encourage you to keep paths consistently as posix, if possible

**Comment by gmaze** [comment]
Thanks !
