### ISSUE TITLE
Files opened from TarFileSystem do not the same interface as LibArchiveFileSystem

### ISSUE THREAD

**Issue by mraspaud** [fsspec/filesystem_spec#938]
In our library, we have a small wrapper around OpenFiles to make them PathLike, and as such, I rely on the `path` (and `fs`) attributes of the OpenFile object. However, when calling `open` on a TarFileSystem, the resulting object does not have `path` nor `fs` attribute, but has a `info` attribute containing the name of the file.
I also observed that ZipFileSystem seems to comply with LibArchiveFileSystem.

Is this deliberate? or is this an ongoing interface change, in which case where are we going to?

Minimal examples:
```python
import fsspec
from fsspec.implementations.libarchive import LibArchiveFileSystem
from fsspec.implementations.tar import TarFileSystem

filename = "/path/to/somefile.tar"

tbfs = TarFileSystem(filename)
first_file = tbfs.find("/")[0]
open_file = tbfs.open(first_file)
print(dir(open_file))

tbfs = LibArchiveFileSystem(filename)
first_file = tbfs.find("/")[0]
open_file = tbfs.open(first_file)
print(dir(open_file))
```

The result:
```
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'close', 'closed', 'end', 'info', 'of', 'read', 'seek', 'size', 'start', 'tell']

['__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__next__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '_checkClosed', '_checkReadable', '_checkSeekable', '_checkWritable', 'close', 'closed', 'commit', 'created', 'detach', 'discard', 'fileno', 'flush', 'fs', 'getbuffer', 'getvalue', 'isatty', 'path', 'read', 'read1', 'readable', 'readinto', 'readinto1', 'readline', 'readlines', 'seek', 'seekable', 'size', 'tell', 'truncate', 'writable', 'write', 'writelines']
```

**Comment by mraspaud** [comment]
I understand. Is this something that you think would be a good feature?
I could have a look at how to add a consistent `__fspath__` method to the different results of  `open()`, that would also make these compatible with the PathLike interface (https://docs.python.org/3/library/os.html#os.PathLike)

**Comment by martindurant** [comment]
I'm not sure that fspath is appropriate, though, since pathlib objects reference the local filesystem explicitly. https://github.com/fsspec/universal_pathlib might have a solution, though.

**Comment by mraspaud** [comment]
Ok, thanks a lot for the pointer. Closing this now as it is a feature, not a bug :)
