### ISSUE TITLE
SFTP / Paramiko is slow

### ISSUE THREAD

**Issue by jobevers** [fsspec/filesystem_spec#948]
I'm seeing similar issues as discussed here:

https://stackoverflow.com/questions/46489543/paramiko-slow-sftp-transfer-speed-compared-with-system-rsync-sftp-scp
https://github.com/paramiko/paramiko/issues/175

I realize this is a paramiko issue, but it might be worth having fsspec set more aggressive defaults as the use case for fsspec / sftp is more likely to involve large files than an SSH session, which is what it seems paramiko is setup for.

**Comment by isidentical** [comment]
Take a look at https://github.com/fsspec/sshfs which is solely designed for speed (on average it beats paramiko up to 4X, and on some circumstances it might go as far as 10X).

**Comment by martindurant** [comment]
We talked about replacing the current implementation in favour of sshfs. We can discuss this again.

**Comment by jobevers** [comment]
I switched to using sshfs and speed did improve.  Thanks!

**Comment by isidentical** [comment]
Glad to hear that, closing this now.
