### ISSUE TITLE
Question: Implementing Backend without Partial Writing

### ISSUE THREAD

**Issue by janjagusch** [fsspec/filesystem_spec#986]
Hi, thanks for maintaining this package! 👍 

I'm trying to build a `fsspec` implementation for [Sonatype Nexus](https://www.sonatype.com/products/nexus-repository). The problem I'm facing is that, to the best of my knowledge, [Nexus doesn't support partial PUTs](https://issues.sonatype.org/browse/NEXUS-33793) and hence it seems impossible to implement the [`upload_chunk`](https://github.com/fsspec/filesystem_spec/blob/9ecef92101194ab4eece8013ce0e3f419b0ccd86/fsspec/spec.py#L1536-L1545) method in `AbstractBufferedFile`.

Most examples seem to either support partial writing (like `s3fs` or `gcfs`) or not support writing at all (like [`httpfs`](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/http.py#L497)). Is there a way to implement a backend that supports partial reading but only supports full writes?

I know this isn't really an issue. If there is a better place to ask this, I'll gladly move this somewhere else.

Thanks in advance for your help!

**Comment by martindurant** [comment]
This is a fine place to ask!

You have a couple of things you could do:
- write your own subclass of `IOBase`, which implements absolutely any logic you like for when and how to write data to remote. This is more work but the most flexible
- use AbstractFileSystem in a slightly non-standard way. There are two methods for writing, `_initial_upload` (a no-op for you) and `_upload_chunk`. The latter takes ` `final=` kwarg - when this is true, you can then write everything in one go, as required by your API. The undocumented trick, is that when it is *not* final, and you therefore have nothing to do, the return value should be `False` to avoid dropping the buffered bytes. Alternatively, you can make the `block_size` so big, that you only ever have one chunk anyway.

Note that in this model, you are writing from an in-memory buffer. To be able to upload larger-than-memory files, you would have to use `put()`, which is actually available in the HTTP(s) backend, and can stream from an open file-like object. You could also stream from an arbitrary callback with some work.

**Comment by janjagusch** [comment]
> model

Thanks for your response, @martindurant! [I also found this SO answer](https://stackoverflow.com/a/72177866/7380270), which also suggests implementing a custom `BaseIO` class for a similar problem. I will give that a try and let you know how that went. 😄

**Comment by janjagusch** [comment]
After a bit of consideration, it seemed more straightforward to use the `final` argument in `_upload_chunk` instead of implementing a custom `IOBase` class from scratch.

One peculiarity was that I had to set the buffer index to 0 before writing, as otherwise, it wouldn't upload the full buffer.

I'm leaving this here as a reference, maybe this will be useful to someone else at some point:

```py
def _upload_chunk(self, final: bool = False) -> bool:
    """Write one part of a multi-block file upload
    Parameters
    ==========
    final: bool
        This is the last block, so should complete file, if
        self.autocommit is True.
    """
    if final:
        # Go to the beginning of the buffer.
        self.buffer.seek(0)
        # Backend-specific implementation for uploading anything BytesIO-like.
        _do_upload(self.buffer, self.path)
        # Return `True` to clear the buffer.
        return True
    # Return `False` to avoid clearing buffer.
    return False
```

@martindurant, is that how you envisioned the implementation as well?

Also, I hope that after some thorough testing I will be able to open-source the code and maybe link it as a supported backend here in `fsspec`. 🤞

**Comment by martindurant** [comment]
Yes, something like that. It is fine to seek in the buffer, given that you will immediately read it all and then it gets discarded anyway. However, the `getbuffer` and `getvalue` methods are there too and may be more convenient.

**Comment by janjagusch** [comment]
Thanks, @martindurant! I think I have enough information to continue from here. I will reach out again once the Nexus fsspec implementation is completed, well-tested, and ready to be open-sourced. 🙂
