### ISSUE TITLE
dircache.__iter__ fails if an item in the cache is expired

### ISSUE THREAD

**Issue by machow** [fsspec/filesystem_spec#987]
Noticed in adlfs (https://github.com/fsspec/adlfs/issues/327).

Since...

* the iter method of dircache uses ends up invoking `__contains__` and `__getitem__`. 
* `__getitem__` will delete expired entries

it looks like iterating over a cache with expired entries can raise:

```python
RuntimeError: dictionary changed size during iteration
```

It seems like having iter get all the underlying entries first in `DirCache._cache` first, and then do the checking and yielding should fix!

(Happy to open a PR if that approach sounds reasonable)

**Comment by martindurant** [comment]
Your reasoning appears sound. You are implying it needs fixing in this repo? Then certainly would be happy to see a PR.

**Comment by machow** [comment]
Hey--yeah, I think fixing here should resolve the issue for adlfs. I can take a quick pass at it next week
