### ISSUE TITLE
`filesystem.put` has non idempotent behavior

### ISSUE THREAD

**Issue by cicdw** [fsspec/filesystem_spec#997]
It seems that `filesystem.put` does something unexpected when called twice, independently of the underlying filesystem.  For example, set up the following directory:
```
mkdir put-test
cd put-test
touch file_one.txt
mkdir nested
touch nested/file_two.txt
```
So that you have:
```
.
|____file_one.txt
|____nested
| |____file_two.txt
```

Next, take a completely empty s3 bucket called `my-bucket` and run the following from within `put-test`:

```python
import fsspec 

fs = fsspec.filesystem("s3")
fs.put("**", "s3://my-bucket/test/", recursive=True)
```

You'll find the following structure within your bucket as expected:

```
test
|____file_one.txt
|____nested
| |____file_two.txt
```

Now run the `put` command a second time, whether in the same session or in a brand new session:
```python
fs.put("**", "s3://my-bucket/test/", recursive=True)
```

And you'll find something surprising in your s3 bucket:

```
test
|____put-test
| |____file_one.txt
| |____nested
| | |____file_two.txt
|____file_one.txt
|____nested
| |____file_two.txt
```

i.e., your parent directory `put-test` has now been nested within the `test` directory of your bucket.  It seems this behavior is consistent across Azure and GCS as well.

Any guidance on whether this is a bug, or whether my `glob` pattern is somehow stateful would be appreciated.

**Comment by martindurant** [comment]
The behavious broadly follows what you would expect on a (posix) command line: when copying a file tree, if you put the destination as a new path, the tree will be created at that point, and the original root directory will be reflected in the new directory which matches the destination path. If you put the destination as an *existing* directory, the tree will be copied inside of it. So the difference isn't first and second run, but whether the destination exists or not. On s3/gcs, the existence of a directory is a little ill-defined, but the behaviour you see seems right to me.
